### ISSUE TITLE
Support for target objects with non-iterger primary keys?

### ISSUE THREAD

**Issue by robbyt** [justquick/django-activity-stream#148]
For one of our models, we use a UUIDField for a pk, via `uuid = UUIDField(primary_key=True, auto=True)` which returns a string-like UUID object. There are a few areas in the code that I think assume the obj.pk is an int.

**Comment by jdcaballerov** [comment]
urls, for instance. All the object_id regex are as follows: (?P<object_id>\d+)

**Comment by jdcaballerov** [comment]
@robbyt I guess it's late but for the record. Just changing the regex for the object_id on the urls seems to work. In urls.py change (?P<object_id>\d+) which assumes integer pk  to (?P<object_id>[^/]+) to allow for any character except /
