### ISSUE TITLE
Feature request: Store actions made by anonymous users

### ISSUE THREAD

**Issue by goldan** [justquick/django-activity-stream#16]
Thanks for the great app.

I'd like to be able to store actions done by anonymous users. A simple solution would be to allow actor and actor_object_id to be None. A more complicated one is to store IP as actor identifier. Is this possible and/or planned?

**Comment by pknowles** [comment]
Is there anything wrong with just allowing a null actor? For example,

    #in action_handler (pls excuse compact code)
    if actor is None and not settings.ALLOW_NULL_ACTOR:
        raise Exception(...)
    ...
    actor_content_type = ContentType.objects.get_for_model(actor) if actor is not None else None,
    actor_object_id = actor.pk if actor is not None else 0,
