### ISSUE TITLE
Django 1.6 defaults removed from django.conf.urls

### ISSUE THREAD

**Issue by mayuroks** [justquick/django-activity-stream#163]
I simply tried to follow a model and i got this error

ImportError
Exception Value:     No module named defaults

In my urls.py
from django.conf.urls import patterns, include, url

and I cannot import defaults

Also i looked into it and found in Django 1.5
NAME
    django.conf.urls

PACKAGE CONTENTS
    defaults
    i18n
    shortcut
    static

Whereas in Django 1.6
NAME
    django.conf.urls

PACKAGE CONTENTS
    i18n
    shortcut
    static

Can you release a newer package version with no dependency on defaults ?

**Comment by jajodiaraghav** [comment]
I am using version 0.6.3 on Django 1.10 and the error still persist

**Comment by auvipy** [comment]
use from master branch

**Comment by auvipy** [comment]
update your code following official django docs
