### ISSUE TITLE
Best practice to localize activities

### ISSUE THREAD

**Issue by jarus** [justquick/django-activity-stream#181]
Hi,

what is the preferred way to localize activities? I my eyes the best way would be to translate the complete message based on verb:
 
```
Englisch "%(actor)s created %(comment)s to %(article)s"
German "%(actor)s hinterließ %(comment)s unter %(article)s"
```

Best regards

**Comment by rolandgeider** [comment]
Has there been some progress on this? Is there something I could help you with (testing, etc.)?

**Comment by jaineshp** [comment]
How to make the activity feed real-time?
