### ISSUE TITLE
Unicode when following object

### ISSUE THREAD

**Issue by brunoamaral** [justquick/django-activity-stream#201]
I have a record called "Sérgio" and when following, the admin view of follows breaks  with `UnicodeDecodeError` 

This started happening when I was trying out the template tags for following objects but I was able to see the same behaviour on the shell:

```
In [80]: follow(user, band)
Out[80]: <Follow: [Bad Unicode data]>
```

**Comment by Nacturne** [comment]
Hi @brunoamaral , maybe it's too late, but I had the same problem as yours and now I figured it out. 

To solve it, you should find the models.py file in act stream app folder. The look at the `class Follow`. Beginning from line 40, you will find:
`def __str__(self):`
     ` return '%s -> %s' % (self.user, self.follow_object)`

Now change this to:
`def __str__(self):`
       `user='%s' % (self.user,)`
        `follow_object='%s' % (self.follow_object,)`
        `return user.decode('utf8')+u' -> '+follow_object.decode('utf8')`

Then everything will work fine.(Note that you should do the appropriate indent, which I can't do in this comment area)

If you want to know the details:

 return '%s -> %s' % (self.user, self.follow_object)` will generate a result encoded in ASCII format. However, a Class in Django expects  its `__str__` method to return a result encoded in uff-8 format. What I did is just converting the result to uff-8 format.  

Hope this will help. By the way the django-activity-stream is really a great job!

**Comment by ProDG** [comment]
Looks like the issue is still here. When I'm trying to go to Actstream / Follows in Django's Admin interface, i get the error:

UnicodeDecodeError at /admin/actstream/follow/
'ascii' codec can't decode byte 0xd0 in position 26: ordinal not in range(128)

**Comment by t-book** [comment]
HI @justquick I think this is still in issue with 0.8.0 

try to change an action verb in django admin to 'gelöscht'

> UnicodeEncodeError at /de/admin/actstream/action/46/change/
> 'ascii' codec can't encode character u'\xf6' in position 9: ordinal not in range(128)

Is there anything we can do about it?
