### ISSUE TITLE
following() always returns objects of NoneType

### ISSUE THREAD

**Issue by jmound** [justquick/django-activity-stream#209]
django-activity-stream==0.5.1
What's going on here? Why does following() return NoneType objects?

```
>>> from actstream.actions import follow
>>> a = TRUser.objects.first()
>>> a
<TRUser: a>
>>> b = TRUser.objects.get(id=5)
>>> b
<TRUser: b>
>>> follow(b,a)
<Follow: f42b0d15-7a3f-473f-a4e6-aba8a1 -> a>
>>> followers(a)
[<User: f42b0d15-7a3f-473f-a4e6-aba8a1>]
```

Everything is fine up to this point. Then when I try following() I get:

```
>>> following(b)
[None]
>>> type(following(b)[0])
<type 'NoneType'>
```

I thought perhaps the issue was that TRUser is not a subclass of User, but I see the same behavior when I use a django User.

**Comment by fynjah** [comment]
Probably got similar problem here #245
