### ISSUE TITLE
Non-standard project structure throws ImproperlyConfigured exception

### ISSUE THREAD

**Issue by davepgreene** [justquick/django-activity-stream#215]
Assuming a project structure like so (Django 1.6.5):

```
project_root
|-- manage.py
|-- wsgi.py
|-- gunicorn.py
|-- webapp
    |-- __init__.py
    |-- urls.py
    |-- app1
        |-- __init__.py
        |-- urls.py
        |-- models
            |-- model1.py
            |-- model2.py
            |-- model3.py
        |-- views
            |-- ...
    |-- app2
        |-- ...
    |-- settings
        |-- ...
```

Attempting to register a model (for example, `webapp.app1.models.Model1`) raises an `ImproperlyConfigured` exception saying:
> The model \<class 'webapp.app1.models.model1.Model1'\> is not installed, please put the app "app1" in your INSTALLED_APPS setting.

This is caused by the `is_installed()` method in `registry.py`, specifically [line 58](https://github.com/justquick/django-activity-stream/blob/0.5.1/actstream/registry.py#L58) which returns everything before `app1` include `webapp` and then tests that string against `django.conf.settings.INSTALLED_APPS`.

The best way (IMHO) is to test against `model_class._meta.app_label`.

**Comment by justquick** [comment]
how are you adding your app to INSTALLED_APPS? also it looks like webapp/app1/models is missing an __init__.py which could be causing the issue

**Comment by elcolie** [comment]
For my case it is `__init__.py` needs to put `default_app_config`
Here is my sample
 `default_app_config = 'multy_herr.objections.apps.ObjectionsConfig'`
