### ISSUE TITLE
documentation on registering the User model

### ISSUE THREAD

**Issue by brunoamaral** [justquick/django-activity-stream#216]
This is more of a suggestion: I am using Userena with actstream, and I am not at all sure if I did this right to register the User model.

```
class StubsConfig(AppConfig):
	name = 'stubs'

	def ready(self):
		registry.register(self.get_model('Band'))
		registry.register(self.get_model('Concert'))
		registry.register(self.get_model('Location'))
		from django.contrib.auth.models import User
		registry.register(User)
````
Either way it would be nice to mention in the docs the right way to register the user model.

**Comment by leesolway** [comment]
I am having the same issue with a custom user ?

**Comment by end0** [comment]
Not sure for <1.7, but for 1.7, if you want to register models outside of the current app, you can do the following. For my use case, I created a wholly separate "activity" app which points to both the User model and the models on which I want actions. According to the [Applications docs](https://docs.djangoproject.com/en/1.7/ref/applications/#application-registry) you can call up any registered app by using the *app_label.model* syntax

    from django.apps import AppConfig, apps
    from actstream import registry


    class ActivityConfig(AppConfig):
        name = 'activity'

        def ready(self):
            registry.register(apps.get_model('auth.user')) #registers the User (assuming you're using auth.User)
            registry.register(apps.get_model('pace.case')) #registers the other apps
            registry.register(apps.get_model('pace.attorney'))
            registry.register(apps.get_model('pace.judge'))
            registry.register(apps.get_model('pace.party'))
            registry.register(apps.get_model('pace.firm'))

**Comment by AlexRiina** [comment]
Is there any reason not to register `settings.AUTH_USER_MODEL` (given django version high enough)? That seems preferable to calling get_model or importing User directly from contrib.auth.

**Comment by leesolway** [comment]
I managed to get around this issue by creating an app solely for registering the custom user model against activity stream and included in installed apps just before referencing activity stream.

**Comment by justquick** [comment]
@AlexRiina  i dont want to add the AUTH_USER_MODEL as actionable by default as there could be some use cases where you would not want that

**Comment by jaineshp** [comment]
How to register the rest of models from models.py by using asdator's solution ? Django version=1.8

**Comment by asdator** [comment]
Actually I migrated my models registration into a separate app like `end0`. Now my code looks like: 

    from actstream import registry
    from django.apps import AppConfig
    from django.apps import apps as django_apps

    class StreamsConfig(AppConfig):
        name = 'myproject.streams'

        def ready(self):
            registry.register(django_apps.get_model('auth','User'))
            registry.register(django_apps.get_model('core', 'UserProfile'))
            registry.register(django_apps.get_model('anotherapp', 'AnotherModel'))

**Comment by jaineshp** [comment]
@asdator : While performing the operations via shell it shows that the model User is not registered. Again the same problem.

**Comment by jaineshp** [comment]
@asdator : I have an app named "questions" in my project "college", and three classes in my models.py needs to be registered, User(django.contrib.auth),Question,Answer. How is it possible without creating a new app?

**Comment by jaineshp** [comment]
@end0 : It shows the error,after creating a new app 'activity', and commenting "django.contrib.auth" and adding "activity.apps.ActivityConfig" in INSTALLED_APPS . Please help!

      class User(AbstractUser):

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in         execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in     execute
        django.setup()
      File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 89, in populate
        "duplicates: %s" % app_config.label)
    django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates:     activity

**Comment by asdator** [comment]
@jaineshp from this stack trace it seems like you should not name your app activity. Name it something else.

**Comment by jaineshp** [comment]
@asdator : I named it "regstreams" and it gave the same error.

**Comment by asdator** [comment]
Can you post your `settings.INSTALLED_APPS`

**Comment by jaineshp** [comment]
@asdator :

    INSTALLED_APPS = [
        'django.contrib.admin',
       # 'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.sites',
        'questions',  #This is my main app
        'notifications',
        'sslserver',
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        'allauth.socialaccount.providers.facebook',
        'allauth.socialaccount.providers.twitter',
        'allauth.socialaccount.providers.google',
        'multiselectfield',
        'regstreams', #App just for registering models
        'regstreams.apps.ActivityConfig',
        'actstream',
    ]

apps.py in regstream:

    from django.apps import AppConfig, apps
    from actstream import registry
    class ActivityConfig(AppConfig):
        name = 'regstreams'

        def ready(self):
            registry.register(apps.get_model('auth.User')) 
            registry.register(apps.get_model('questions.quest')) #quest is the name of class in models.py of 'questions' app

**Comment by asdator** [comment]
Ok I think I understand what the problem is, you are registering your `regstreams` app twice.
remove the 'regstreams.apps.ActivityConfig' from `INSTALLED_APPS` and inside `__init__.py` in your `regstreams` folder put `default_app_config = 'regstreams.apps.ActivityConfig'`. This way when `Django` register `regstreams` it will use your custom `ActivityConfig`.

**Comment by jaineshp** [comment]
@asdator :Now it says

    LookupError: No installed app with label 'auth'.

**Comment by jaineshp** [comment]
It worked! Thanks a lot for your help :)

**Comment by jaineshp** [comment]
I had another doubt, how to set the target of action to the followers of that user?
