### ISSUE TITLE
Undocumented "public" attribute for action signal

### ISSUE THREAD

**Issue by end0** [justquick/django-activity-stream#222]
Currently, docs don't mention the "public" kwarg that can be passed to an action signal. public is a boolean that enotes whether an action is public or private. The managers and other components of the system utilize it, so would be good to add it into the docs, as I had to dig into the source to find mention of it. Happy to give this a shot with a PR if you're ok with it.

**Comment by ryangallen** [comment]
Bump. Looks like the docs could use some TLC.

**Comment by justquick** [comment]
@end0 have at it. thanks!
