### ISSUE TITLE
Using actions as notification and marking as "seen"

### ISSUE THREAD

**Issue by ryangallen** [justquick/django-activity-stream#224]
What is the best way to show new activity to a user, mark it as "seen" or "read" to not show it again.

Should there not be an "active" boolean on the Action model?

**Comment by michaeljones** [comment]
I think you need a separate model to track the 'read' status for each user. Generally in a system with many users you need to track the 'read' status for each one so it can't be in a central place like on the `Action` model.

Unless I'm getting confused? :)

**Comment by michaeljones** [comment]
For reference, I have a project with a notification system layered on top of `django-activity-stream`. The Notification model looks like this:

```python
class Notification(models.Model):

    action = models.ForeignKey(Action)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    unread = models.BooleanField(default=True)
    important = models.BooleanField(default=False)

    data = CustomJSONField(default={})

    site = models.ForeignKey(Site)

    # Default manager
    objects = models.Manager()
    on_site = CurrentSiteManager()

    def __unicode__(self):
        return u"{user}: {action}".format(user=self.user, action=self.action)

    def has_title(self):
        return 'title' in self.data

    def has_message(self):
        return 'message_template' in self.data
```

I'm not very experienced though, so I can't speak as to how good an approach this is.

**Comment by ryangallen** [comment]
@michaeljones that makes sense and I did think of that. I was thinking the action target would be the intended recipient. Is that not what the target is for?

**Comment by michaeljones** [comment]
My understanding is that the `target` is the target of the action being described. ie. you might want to notify user `bob` that `alice` has friended `charles`. In that case, `charles` would be the target. `bob` is the user you'd like to associated the `read/unread` status with but the `target` of the `Action` is `charles`.

There are some brief docs in the [class' docstring](https://github.com/justquick/django-activity-stream/blob/master/actstream/models.py#L62). 

I might be wrong though :)

**Comment by ryangallen** [comment]
I think you're exactly right. Thank you for the clarification.
