### ISSUE TITLE
Support for builtin migrations

### ISSUE THREAD

**Issue by rvianello** [justquick/django-activity-stream#227]
It looks like that the application supports South, but it doesn't support the built-in migration framework, am I correct?

Is there any reason for this, or is it in the plans?

Thanks,
riccardo

**Comment by abdoukarim** [comment]
This post resolved the problem for me using django vers 1.8
https://github.com/evonove/django-oauth-toolkit/issues/204#issuecomment-77984967

I had this error when running tests for my app
```
Creating test database for alias 'default'...
Got an error creating the test database: database "test_myapp" already exists

Type 'yes' if you would like to try deleting the test database 'test_myapp', or 'no' to cancel: yes
Destroying old test database 'default'...
Traceback (most recent call last):
django.db.utils.ProgrammingError: relation "auth_user" does not exist
```

I solved that problem by adding this in the settings:
```
MIGRATION_MODULES = {
   # key: app name, value: a fully qualified package name, not the usual `app_label.something_else`
  'actstream': 'my_project.migrations.actstream',
}
```
Then run ```python manage.py makemigrations actstream``` to generate a new migration for actstream

**Comment by justquick** [comment]
added new migrations and moved south migrations to actstream.south_migrations. docs on the switch to follow but the new migrations are now in master

**Comment by rvianello** [comment]
Thank you so much @justquick
