### ISSUE TITLE
Problem when using UUID as objects Primary Keys

### ISSUE THREAD

**Issue by jdcaballerov** [justquick/django-activity-stream#228]
Hi,

I think that with the new Django 1.8 which now has a built in UUID field usable as primary key there will be problems since all the urls assume integers (regex: \d+)  for object_id.

Any suggestions to start addressing the issue? I am not familiar with the codebase. I´ll be glad to help.

best,

update: Changing the regex in the urls for object_id to (?P<object_id>[^/]+) seems to work.

**Comment by justquick** [comment]
good call. fixed in master
