### ISSUE TITLE
Ability to call <object>.any_actions, similar to .target_actions

### ISSUE THREAD

**Issue by benbacardi** [justquick/django-activity-stream#229]
Most streams provide a convenience method on the object so you don't have to import the function from `actstream.models`. However, the [any_stream](https://django-activity-stream.readthedocs.org/en/latest/streams.html#any-streams) doesn't. Could this possibly be provided?

```python
>>> object.any_actions.all()
```

**Comment by justquick** [comment]
unfortunately those handy helpers are GenericRelatedObjectManagers and django sets them up internally when using GenericRelations. there are only 3 (actor/target/object) which are setup so you will have to use those or use the any_stream helper function.
