### ISSUE TITLE
Deleted targets are not shown

### ISSUE THREAD

**Issue by corebyte** [justquick/django-activity-stream#230]
I have some actions that are created as 'created' Comment

But when a Comment is deleted

i want to let it show in the activity stream that Comment with name x Y is deleted.

please help me, this could be it for my use as a in app stream handler but it must also show deleted actions.

**Comment by justquick** [comment]
i think the only answer is to not actually delete the record but mark it as deleted w/ a boolean (like actions do with the 'public' attribute). when you delete an object in django, the gfk will always return None so any extra functionality is up to your project's implementation
