### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by andreykko** [justquick/django-activity-stream#231]
Hi, thanks for library! 
But I have some issues:
![Error](https://pp.vk.me/c624823/v624823041/29bc2/pEN3pzzl5gE.jpg) - in admin, and I get None of Actor and etc when grab user feed. User model is registered. 
Can someone help me plz?
Problem in admin only on python 3.4, on 2.7 admin work fine, but problem with None still exist.

**Comment by jdcaballerov** [comment]
Python 3 does not define the type basestring. The other issue might be that you are not following the object thus not getting the actions.

**Comment by justquick** [comment]
notice that error is in the jsonfield package and not part of this app. try upgrading django-jsonfield
