### ISSUE TITLE
How to get the custom data added to the action on custom feeds

### ISSUE THREAD

**Issue by jdcaballerov** [justquick/django-activity-stream#232]
Hi,
Is there any way to get the custom data (json field) added to the action on Custom Feeds ?

As far as I can get from the code one way is to alter the function "format" in AbstractActivityStream . I think one can easily detect if the user is using the field using the setting ACTSTREAM_SETTINGS['USE_JSONFIELD'] and thus including it.

Best,

**Comment by justquick** [comment]
what custom data are you planning to add and to which field in the feed (atom or json) are you planning to add it? adding custom named fields to the atom/json feeds would violate the specifications so im wondering what you are planning to add and whether it adheres to the spec

**Comment by jdcaballerov** [comment]
I mostly use django as a backend. Let´s say I need to use the custom data as described [in the documentation](http://django-activity-stream.readthedocs.org/en/latest/data.html) on a [Custom JSON feed](http://django-activity-stream.readthedocs.org/en/latest/feeds.html). I am not sure if it complies with the standard, but its a functionality offered by the package non accessible in JSON feeds.

For my use case I decided to override the function "format" in AbstractActivityStream and just include it. I wonder if there is way to include it in feeds and comply with the standard. 

Excellent package !

**Comment by justquick** [comment]
yea overriding format is the best approach. i dont think the base implementation will change to account for custom data as that might break the spec and it's also not a requirement of the app. having some docs on what you went through to make it happen would be helpful though. could you write up a quick guide?

**Comment by jdcaballerov** [comment]
Yes, sure. Ill paste it here. It is basically overriding all classes to get to AbstractActivityStream and add the extra key to the dictionary (error detection is not done). Maybe something shorter can be done but I preferred the verbose approach

1. Follow the instructions to [add custom data](https://django-activity-stream.readthedocs.org/en/latest/data.html)
2. Define a package activity or your preferred name
3. Override AbstractActivityStream (activity/feeds.py)
```
import json

from django.http import HttpResponse
from django.views.generic import View
from django.utils.feedgenerator import rfc3339_date
from django.utils.six import text_type

from actstream.feeds import AbstractActivityStream,CustomStreamMixin

class MyAbstractActivityStream(AbstractActivityStream):
    def format(self, action):
        """
        Returns a formatted dictionary for the given action.
        """
        item = {
            'id': self.get_uri(action),
            'url': self.get_url(action),
            'verb': action.verb,
            'published': rfc3339_date(action.timestamp),
            'actor': self.format_actor(action),
            'title': text_type(action),
        }
        if action.description:
            item['content'] = action.description
        if action.target:
            item['target'] = self.format_target(action)
        if action.action_object:
            item['object'] = self.format_action_object(action)
        if action.data:
            item['data'] = action.data

        return item

class MyJSONActivityFeed(MyAbstractActivityStream, View):
    """
    Feed that generates feeds compatible with the v1.0 JSON Activity Stream spec
    """
    def dispatch(self, request, *args, **kwargs):
        return HttpResponse(self.serialize(request, *args, **kwargs),
                            content_type='application/json')

    def serialize(self, request, *args, **kwargs):
        items = self.items(request, *args, **kwargs)
        return json.dumps({
            'totalItems': len(items),
            'items': [self.format(action) for action in items]
        }, indent=4 if 'pretty' in request.REQUEST else None)

class MyCustomJSONActivityFeed(CustomStreamMixin, MyJSONActivityFeed):
    """
    JSON feed of Activity for a custom stream. self.name should be the name of the custom stream as defined in the Manager
    and arguments may be passed either in the url or when calling as_view(...)
    """
    pass
```
4. Optionally define a manager(activity/managers.py)
```
from datetime import datetime

from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404

from actstream.managers import ActionManager, stream
from actstream.registry import check

class MyActionManager(ActionManager):

    @stream
    def mystream(self, content_type_id,object_id,**kwargs):
        obj_content = get_object_or_404(ContentType, pk=content_type_id)
        obj = obj_content.get_object_for_this_type(pk=object_id)
        return obj.target_actions.public(**kwargs)

```
5.Add a url

```
from activity.feeds import MyCustomJSONActivityFeed
url(r'^feed/history/(?P<content_type_id>\d+)/(?P<object_id>[^/]+)/json/$',
    MyCustomJSONActivityFeed.as_view(name='mystream')),

```

**Comment by justquick** [comment]
the data is in the right place but needs to be added to the xml feed using django's syndication framework. try looking into how it works in actstream/feeds.py: https://github.com/justquick/django-activity-stream/blob/master/actstream/feeds.py#L143

**Comment by jdcaballerov** [comment]
Thanks, I forgot to mention I only use json feeds so the former works well.
