### ISSUE TITLE
migration error on acstream_follow

### ISSUE THREAD

**Issue by avances123** [justquick/django-activity-stream#240]
It tries to make a foreign key to auth.user (or default user model) before it is created.

Solved with 2-step:

```
python manage.py migrate auth
python manage.py migrate
```

But can't run tests because of the same error in test database creation.

python3.4 django 1.8 and postgresql 9.4

**Comment by avances123** [comment]
I just realized they are south migrations, 

I will use https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES if you confirm in django 1.8 migrations are broken

**Comment by justquick** [comment]
new migrations are now in master and soon to be released
