### ISSUE TITLE
TemplateSyntaxError - actor_url

### ISSUE THREAD

**Issue by harisbeha** [justquick/django-activity-stream#242]
I tried installing django-activity stream according to the directions. Everything is installed based on default settings. I'm currently getting the following error: 

TemplateSyntaxError at /activity/
Invalid block tag: 'actor_url', expected 'elif', 'else' or 'endif'
Request Method:	GET
Request URL:	mysite/activity/
Django Version:	1.5.5
Exception Type:	TemplateSyntaxError
Exception Value:	
Invalid block tag: 'actor_url', expected 'elif', 'else' or 'endif'
Exception Location:	/home/ubuntu/pitch/local/lib/python2.7/site-packages/django/template/base.py in invalid_block_tag, line 327

**Comment by AlexRiina** [comment]
Do you have `{% load activity_tags %}` in your template?

**Comment by harisbeha** [comment]
Right now I was just using the default templates in the activity stream folder, but yes the tag is there.

**Comment by harisbeha** [comment]
I realized I didn't have the ACTSTREAM_SETTINGS added to my settings file. Now I'm getting this error:

  File "/home/ubuntu/pitch/local/lib/python2.7/site-packages/actstream/registry.py", line 39, in setup_generic_relations
    setattr(Action, attr_value, None)
AttributeError: 'NoneType' object has no attribute 'actions_with_auth_user_as_actor'

**Comment by harisbeha** [comment]
Okay, another breakthrough. 

I think my issue was coming from trying to register the generic User model from django contrib auth. 

Is there an alternate way to register the user model than registry.register(User)

Now I have an issue with the settings: 

ImportError: Cannot import myapp.managers.MyActionManager try fixing ACTSTREAM_SETTINGS[MANAGER]setting.

**Comment by harisbeha** [comment]
Okay, fixed all of those issues. Now I just need to figure out how to register the generic user model. The other issue about this doesn't really explain the process.

**Comment by harisbeha** [comment]
Did get_user_model() and it seems to work now.
