### ISSUE TITLE
Potential For nullable actor

### ISSUE THREAD

**Issue by jpulec** [justquick/django-activity-stream#243]
I'm wondering if there is any sense in making ```actor``` a nullable field. I have a use case where I'm tracking the actions of my users, but also want to track if the same actions happened automatically.

For example, write a record whenever an actor placed an order, but also write a record whenever an order was placed automatically by one of our scheduled celery tasks.

I think this breaks the JSON spec ( :sob: ), so I could understand a lot of reasons for not doing it. But I'm also wondering if anyone else has run into this use case, and how they may have solved it.

**Comment by justquick** [comment]
sorry that breaks the spec so i cant include it here. you could always fork it
