### ISSUE TITLE
'ascii' codec can't decode byte 0xd1 in position 6: ordinal not in range(128) when accessing admin interface

### ISSUE THREAD

**Issue by rzinurov** [justquick/django-activity-stream#244]
Hi guys,

When I try to open activity list in Django admin interface I'm getting this error:
```
'ascii' codec can't decode byte 0xd1 in position 6: ordinal not in range(128)
```
I think this happens because I have cyrillic characters in action target field. This issue was also reproducible with `django-notifications-hq==0.6.2` which was derived from this app, but it's fixed in version 0.7.0. Please let me know if there is any temporary workaround. I'm using `django-activity-stream==0.5.1`

`django-notifications-hq` issue:
https://github.com/django-notifications/django-notifications/issues/63

**Comment by justquick** [comment]
can you please post a traceback? also a complete example demonstrating the problem would be helpful. the solution in django-notifications does not account for ugettext translation

**Comment by rzinurov** [comment]
I've just checked version 0.6.0 and it seems like the issue is solved there. Sorry for bothering.

**Comment by jdcaballerov** [comment]
I had a similar issue when using another language since djtimesince returns translated names for day and hour. The problem came from here (django-activity-stream/actstream/models.py):

```
    def timesince(self, now=None):
        """
        Shortcut for the ``django.utils.timesince.timesince`` function of the
        current timestamp.
        """
        return djtimesince(self.timestamp, now).encode('utf8').replace(b'\xc2\xa0', b' ').decode('utf8')
```

In version 0.6.0 is neither a problem for me.
