### ISSUE TITLE
action_object not being saved

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [justquick/django-activity-stream#246]
I'm using `django-threaded-comments` app to handle the comments. When I try to create the action, all is saved except the comment instance, which is a `ThreadedComment` instance.
Code:
```python
@receiver(comment_was_posted, dispatch_uid="default_comment_posted_handler")
def comment_posted_handler(sender, comment, request, **kwargs):
    action.send(request.user, verb="commented", 
                action_object=comment, target=comment.content_object,
                comment=comment.comment)
```
It's also notable that saving the comment as custom data as above doesn't work either.

**Comment by justquick** [comment]
are you sure the comment_posted_handler signal is being called? also try using Action.objects.create instead of action.send and see if you have any luck with that approach

**Comment by github-account-because-they-want-it** [comment]
I think I found the problem. The `stream` decorator is a suspect if you ask me, but I'm not sure what this decorator is doing. Here's a snippet from django console to illustrate what I found:
```python
>>> action1 = admin.actor_actions.public()[0]
>>> action1.action_object
<ThreadedComment: admin: My another comment...>
>>> action1 = Action.objects.actor(admin)[0]
>>> action1
<Action: admin commented Best Rated Video #9 8 hours, 7 minutes ago>
>>> action1.action_object

>>>
```
admin is a `User` object here. When the action is retrieved from the undecorated `public` the returned actions are good. When retrieved from the decorated `actor()`, something goes wrong.

**Comment by justquick** [comment]
the stream decorator not working could actually be related to #245. the decorator is there to add some syntactic sugar but more importantly to ensure that fetch_generic_relations is always called on the querysets otherwise there might be disastrous performance impacts. what happens if you change your first example to `action1 = admin.actor_actions.public().fetch_generic_relations()[0]` ?

**Comment by github-account-because-they-want-it** [comment]
`fetch_generic_relations()` seems to trigger the bug:
```python
>>> action = admin.actor_actions.public().fetch_generic_relations()[0]
>>> action.action_object
>>>
```

**Comment by bufke** [comment]
Can confirm. A work around is to set FETCH_RELATIONS as False in settings.py.

I created a custom feed. Added a breakpoint in format_item. With FETCH_RELATIONS all GFK are None. Without it all work.

If I have time tomorrow I'll submit a failing unit test demonstrating the issue.
