### ISSUE TITLE
Follow template tag not working?

### ISSUE THREAD

**Issue by isaacpeka** [justquick/django-activity-stream#247]
Hi guys, 

Just started using this project, seems really cool :) I'm having a problem at the moment with the `follow` template tag. Specifically, it always returns the "follow" url even when `is_following` returns `True`.

Running the following through the shell everything works ok:

``` python
    from django.contrib.auth.models import User
    from actstream.models import Follow
    from actstream.models import follow, unfollow

    user1 = User.objects.create(username='user1')
    user2 = User.objects.create(username='user2')

    follow(user1, user2)
    Follow.objects.is_following(user1, user2)
    >> True

    unfollow(user1, user2)
    Follow.objects.is_following(user1, user2)
    >> False
```

Here's my template code just for reference, it will always return the "follow" url even when `request.user|is_following:object` returns True:

``` django
    <li> <a href="{% follow_url object %}?next={{request.path}}"> 
        {% if request.user|is_following:object %} Unfollow {% else %} Follow {% endif %}
    </a> </li>
```

I've tr
acked the problem down to the class "actstream.templatetags.activity_tags.DisplayActivityFollowUrl" in the following line of code (line 20): `if Follow.objects.is_following(context.get('user'), actor_instance):`

This returns false because the wrong objects are being compared. The line of code `context.get('user')` is returning `sampeka`, when it should return `you_are_my_friend` (`you_are_my_friend` is the currently logged in user). Seems like a weird bug but interestingly in the String representation of the context there appears to be two `user` fields. Here's the slightly hard to read print out of `context`:

``` python
    [{'True': True, 'False': False, 'None': None}, 
    {'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10fa57630>, 
    'request':<WSGIRequest: GET '/profile/1/'>, 
    'user': <SimpleLazyObject: <User: you_are_my_friend>>, 
    'socialaccount': {'providers': dict_values([])}, 
    'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x10fa5f950>>,
     'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10fa574e0>, 'DEFAULT_MESSAGE_LEVELS': {'SUCCESS': 25, 'ERROR': 40, 'WARNING': 30, 'DEBUG': 10, 'INFO': 20}}, 
    {'view': <social.views.ProfileDetailView object at 0x10fa57978>, 
    'user': <User: sampeka>, 'object': <User: sampeka>}, 
    {'block': <Block Node: content. Contents: [<Text Node: ''>, <django.template.defaulttags.AutoEscapeControlNode object at 0x10fa6ef98>, <Text Node: ''>]>}]
```

Anyway... By changing the line of code to `if Follow.objects.is_following(context.get('request').user, actor_instance)` I've got this to work. Not sure if there's a specific reason you didn't access the user through the request object? I'll submit a pull request but not sure if that will break your build.

**Comment by sampeka** [comment]
The above change failed to pass your tests. Anyone else having this problem or have any ideas how to fix it?

**Comment by justquick** [comment]
which is not working: `is_following` or `follow_url`?

**Comment by sampeka** [comment]
`follow_url`

**Comment by justquick** [comment]
this isnt ideal but see if using the `with` tag works like this:

```html
{% with user=request.user %}
    <li> <a href="{% follow_url object %}?next={{request.path}}"> 
        {% if user|is_following:object %} Unfollow {% else %} Follow {% endif %}
    </a> </li>
{% endwith %}
```

im not sure why it's just checking `user` but that should change

**Comment by sampeka** [comment]
I ended up doing something similar to this  (setting `user` manually in `get_context_data`), seems to be working for now. Thanks a lot again :+1:

**Comment by justquick** [comment]
im leaving this open to remind me to fix that tag to not expect 'user' always in context. there should be some optional arguments in there to sub the value

**Comment by cmwaura** [comment]
@justquick you were right, using {% with user=request.user %} it works but the other way i.e. using request.user doesn't. Took me a while to find this post.
