### ISSUE TITLE
Deadlocks on MySQL with InnoDB

### ISSUE THREAD

**Issue by asdator** [justquick/django-activity-stream#262]
We have a simple functionality for the users allowing them to `CREATE/DELETE` a specific model. 
We also listen for a `post_save` signal to create a new action when a user creates a new model. 
We do NOT listen for `pre/post delete` signals from this model, because `actstream` set up `GenericRelations` for actionable models. This force `django` to simulate `ON DELETE CASCADE` functionality for the created actions.

	def on_new_record(sender, instance, created, **kwargs):
		if created:
			action.send(instance.user, verb='swam', action_object=instance, target=instance.location)

	post_save.connect(on_new_record, sender=Record, dispatch_uid="on_new_record")

With this simple setup, when two users at the same time create and delete one of their records, we get this:

	------------------------
	LATEST DETECTED DEADLOCK
	------------------------
	2015-10-01 00:57:02 2b716ef84700
	*** (1) TRANSACTION:
	TRANSACTION 750478918, ACTIVE 1 sec inserting
	mysql tables in use 1, locked 1
	LOCK WAIT 5 lock struct(s), heap size 1184, 3 row lock(s), undo log entries 1
	MySQL thread id 5778701, OS thread handle 0x2b7246040700, query id 57298086 some_ip dbname update
	INSERT INTO `actstream_action` (`actor_content_type_id`, `actor_object_id`, `verb`, `description`, `target_content_type_id`, `target_object_id`, `action_object_content_type_id`, `action_object_object_id`, `timestamp`, `public`, `data`) VALUES (46, '280196', 'swam', NULL, 44, '39013', 47, '5500621', '2015-09-30 20:06:18', 1, NULL)
	*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
	RECORD LOCKS space id 666 page no 3352 n bits 1104 index `actstream_action_3df58830` of table `dbname`.`actstream_action` trx id 750478918 lock_mode X locks gap before rec insert intention waiting
	Record lock, heap no 601 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
	 0: len 4; hex 8000006e; asc    n;;
	 1: len 4; hex 80020eea; asc     ;;

	*** (2) TRANSACTION:
	TRANSACTION 750478855, ACTIVE 2 sec fetching rows
	mysql tables in use 1, locked 1
	2207 lock struct(s), heap size 243240, 406238 row lock(s), undo log entries 1
	MySQL thread id 5778693, OS thread handle 0x2b716ef84700, query id 57298015 some_ip dbname updating
	DELETE FROM `actstream_action` WHERE (`actstream_action`.`action_object_object_id` IN ('4942966') AND `actstream_action`.`action_object_content_type_id` = 47)
	*** (2) HOLDS THE LOCK(S):
	RECORD LOCKS space id 666 page no 3352 n bits 1104 index `actstream_action_3df58830` of table `dbname`.`actstream_action` trx id 750478855 lock_mode X locks gap before rec
	Record lock, heap no 601 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
	 0: len 4; hex 8000006e; asc    n;;
	 1: len 4; hex 80020eea; asc     ;;

	*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
	RECORD LOCKS space id 666 page no 3284 n bits 192 index `PRIMARY` of table `dbname`.`actstream_action` trx id 750478855 lock_mode X waiting
	Record lock, heap no 124 PHYSICAL RECORD: n_fields 14; compact format; info bits 0
	 0: len 4; hex 8009d63e; asc    >;;
	 1: len 6; hex 00002cbb6646; asc   , fF;;
	 2: len 7; hex fe0000013f0110; asc     ?  ;;
	 3: len 4; hex 8000002e; asc    .;;
	 4: len 6; hex 323830313936; asc 280196;;
	 5: len 4; hex 7377616d; asc swam;;
	 6: SQL NULL;
	 7: len 4; hex 8000002c; asc    ,;;
	 8: len 5; hex 3339303133; asc 39013;;
	 9: len 4; hex 8000002f; asc    /;;
	 10: len 7; hex 35353030363231; asc 5500621;;
	 11: len 5; hex 99973d4192; asc   =A ;;
	 12: len 1; hex 81; asc  ;;
	 13: SQL NULL;

	*** WE ROLL BACK TRANSACTION (1)

[AFAIK](http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans/2423921#2423921), if we change the delete statement to something like:

    DELETE FROM `actstream_action` WHERE `actstream_action`.`id` IN (SELECT `actstream_action`.`id` FROM `actstream_action` WHERE `actstream_action`.`action_object_object_id` IN ('4942966') AND `actstream_action`.`action_object_content_type_id` = 47)

this could possibly fix the problem. But we don't have access to this query since its automatically generated by Django, who [states](https://docs.djangoproject.com/en/1.7/ref/contrib/contenttypes/#reverse-generic-relations) that: 

> Note also, that if you delete an object that has a GenericRelation, any objects which have a GenericForeignKey pointing at it will be deleted as well. In the example above, this means that if a Bookmark object were deleted, any TaggedItem objects pointing at it would be deleted at the same time.
> 
> Unlike ForeignKey, GenericForeignKey does not accept an on_delete argument to customize this behavior; if desired, you can avoid the cascade-deletion simply by not using GenericRelation, and alternate behavior can be provided via the pre_delete signal.

But the `GenericRelation` comes at the [registration level](https://github.com/justquick/django-activity-stream/blob/master/actstream/registry.py#L18) of the `acstream`. So it seems like there is not way to skip this part and manually do the desired `on_delete` behavior.

Any ideas how to avoid this deadlocks? One thing we haven't try yet is to try [to repeat](http://stackoverflow.com/questions/12180637/python-django-script-crashes-on-mysql-deadlock) the transaction on failure, something like:

	def on_new_record(sender, instance, created, **kwargs):
		if created:
			try:
				action.send(instance.user, verb='swam', action_object=instance, target=instance.location)
			except DatabaseError:
				# retry here
				action.send(instance.user, verb='swam', action_object=instance, target=instance.location)

Another thing which we haven't tried yet is to [lower the isolation level](http://stackoverflow.com/questions/11213481/django-db-transactions-and-deadlocks)

We use Django 1.7.x and MySQL 5.6.x

Any help will be appreciated, 10x in advance.

**Comment by justquick** [comment]
No idea how to debug this in MySQL. Havent worked with it in years
