### ISSUE TITLE
Docs mention unfollow_all URL,  which doesn't exist.

### ISSUE THREAD

**Issue by 5a1t** [justquick/django-activity-stream#263]
Docs here:
https://django-activity-stream.readthedocs.org/en/latest/follow.html

mention a URL for unfollow_all:
curl -X GET http://localhost:8000/activity/unfollow_all/<content_type_id>/<object_id>/?next=/blog/ # Unfollow and redirect

but this URL doesn't exist and isn't listed in urls.py.

**Comment by justquick** [comment]
fixed in 85bdea0b3dc4251f3b7cf07f8340041165ca8409
