### ISSUE TITLE
Not compatible with Wagtail

### ISSUE THREAD

**Issue by bufke** [justquick/django-activity-stream#267]
Using this with Wagtail CMS can cause errors when using registry.register with a wagtail Page. 

https://github.com/torchbox/wagtail/issues/1852

Very similar to #48

*Edited - workaround wasn't really a workaround

**Comment by bufke** [comment]
This looks scary. https://github.com/justquick/django-activity-stream/blob/master/actstream/registry.py#L46

Af far as I can tell that function's return relations is always an array of None. If I remove it outright I get error about needing to register the model. If I set it to [] it works fine.

```
class ActionableModelRegistry(dict):

    def register(self, *model_classes_or_labels):
        for class_or_label in model_classes_or_labels:
            model_class = validate(class_or_label)
            if model_class not in self:
                self[model_class] = [] #setup_generic_relations(model_class)
```

It seems like register does nothing at all. Does anyone know how this stuff works? What is the purpose of setting up generic relations? Did at one time it return something more than a bunch of None's? Everything I'm using this project for seems to still work after removing the generic relations.

**Comment by bufke** [comment]
Possible fix but would really like someone to validate this. 

https://github.com/thelabnyc/django-activity-stream/commit/2e53f4ea13eaeaccc3c8087973c558240bace17f

**Comment by justquick** [comment]
@bufke this looks like a good fix but it breaks compatibility for django 1.4-1.6 

```python
  File "/Users/jquick/Projects/django-activity-stream/actstream/registry.py", line 40, in setup_generic_relations
    rel = generic.GenericRelation('actstream.Action', **kwargs)
  File "/Users/jquick/Projects/django-activity-stream/.tox/py27-dj1.4-sqlite/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py", line 164, in __init__
    Field.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'related_query_name'
```

make sure to run tox first: `tox -e py27-dj1.4-sqlite`

**Comment by auvipy** [comment]
I left a comment on the updated PR

**Comment by auvipy** [comment]
could you try the master branch with upcoming wagtail 2.2?
