### ISSUE TITLE
Django creates migration for actstream after Foreign key to Action

### ISSUE THREAD

**Issue by Q-bart** [justquick/django-activity-stream#278]
Hello! 

I have created own model Notification. There is foreign key to actstream  Action:

```
class Notification(models.Model):
    user = models.ForeignKey(User)
    action = models.ForeignKey(Action)
    is_read = models.BooleanField(default=False)

```

And when I run `manage.py makemigrations myapp` django creates one more migration for actstream.
Here it is:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='data',
        ),
    ]

```

So what should I do?

Can I migrate it? But in which way will I migrate it in deploy?

**Comment by justquick** [comment]
what is your use case? im not sure what problem you are trying to solve but generally a fk to an action isnt the way to go about it

**Comment by andyfoundi** [comment]
I just upgraded from 0.5 to 0.6 and faced the same problem. Somehow when running migration, it suggests me to run makemigrations. When I do, it creates the exact same output as Q-bart mentioned.

Any idea?

**Comment by justquick** [comment]
is you app doing a fk to Action too?

**Comment by andyfoundi** [comment]
I don't think we have a fk to Action.

I found something strange though, in 0.5.1 (the version I used to have), there is one migration:
0006_auto__add_field_action_data.py
`
    class Migration(SchemaMigration):

        def forwards(self, orm):
            # Adding field 'Action.data'
            db.add_column('actstream_action', 'data', self.gf('django.db.models.fields.TextField')(null=True, blank=True), keep_default=False)
        ...
        ...
        models = {
            'actstream.action': {
               'data': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
`

It seem the `data` field is there, but when I look in the `models.py`, I couldn't find the data field in Action.
I checked the latest code, the `models.py` doesn't have data field either, but it exists in `0001_initial.py`

Is it something that migration is complaining about?

**Comment by graup** [comment]
Just ran into the same problem. Django is complaining about missing migrations, and `manage.py makemigrations` wants to create a migration for actstream.

```
Migrations for 'actstream':
  0002_remove_action_data.py:
    - Remove field data from action
```

**Comment by justquick** [comment]
i need more info like which version of python and django you are using. also i need to know what the value that this returns:

```python
>>> from actstream.settings import SETTINGS
>>> print(SETTINGS)
```

**Comment by andyfoundi** [comment]
Here is my environment,

Python version
```
$python --version
Python 2.7.6
```
In [1]: from actstream.settings import SETTINGS

In [2]: print(SETTINGS)
{}
```
```
$pip freeze | grep act
django-activity-stream==0.6.0

$pip freeze | grep Django
Django==1.8.8
```

**Comment by graup** [comment]
Here is my env. I installed actstream from git commit f725aaf73a42812793b5feeaa4900458e5e11edf
```
$ python --version
Python 3.5.1
```
```
>>> from actstream.settings import SETTINGS
>>> print(SETTINGS)
{}
```
```
$ pip freeze | grep act
django-activity-stream==0.6.1
$ pip freeze | grep Django
Django==1.9
```

**Comment by justquick** [comment]
yea i fat fingered that one. the new migration is in 1f4cb9981a1a5adead66008dfa4f5a5235e6c89d but you have to make sure USE_JSONFIELD=False to remove the data field

**Comment by andyfoundi** [comment]
Hi justquick,
Thanks for the fix. Just to be clear, this is what I need to do to fix it.

1. update activity-stream to the latest (to include 1f4cb99)
2. set USE_JSONFIELD=False
3. run migration again and data will be removed

Does that sound right?
Thanks

**Comment by justquick** [comment]
yea just try this against master for now. im adding this in 0.6.2 which should come out soon. let me know if it works for you ok:

pull from master. change setting:
```python
ACTSTREAM_SETTINGS = {
    'USE_JSONFIELD': False
}
```
django-admin.py migrate actstream

**Comment by andyfoundi** [comment]
Cool, will try it. Thanks for the help

**Comment by andyfoundi** [comment]
Hi, 
It is working now. 
I need to do `./manage.py migrate --fake` first though.
