### ISSUE TITLE
Inconsistent values of send_action

### ISSUE THREAD

**Issue by avorio** [justquick/django-activity-stream#280]
What is the reasoning behind the inconsistent values of `send_action`?

Here it is `True`:

```python
def follow(user, obj, send_action=True, actor_only=True, **kwargs):
```

Here it is `False`:

```python
def unfollow(user, obj, send_action=False):
```

I'd expect to see an action after unfollowing someone/something, specially after an action was created when I followed them in the first place.

More importantly, is it possible to change these default values using `settings.py`?

**Comment by justquick** [comment]
there are some use cases where you do not want an action created when you follow/unfollow someone which is why it's handled by arguments to the signal. it is up to your app to use it correctly on a case by case basis and there's no way to globally override this in your settings
