### ISSUE TITLE
Filtering on action_object: Field 'action_object' does not generate an automatic reverse relation and therefore cannot be used for reverse querying.

### ISSUE THREAD

**Issue by graup** [justquick/django-activity-stream#281]
Hi! I used your example from https://github.com/django-notifications/django-notifications/issues/64#issuecomment-111934724 to add a Notification model that is saved as the `action_object`.

However, when in the stream I try to `return sender.actor_actions.filter('action_object__read': False)` (`sender` ist the current user), Django fails with `Field 'action_object' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.`

I don't really understand this error, because I am not actually querying in reverse here, am I?

Any ideas?

**Comment by justquick** [comment]
please post the python code you are using and the full traceback of the error

**Comment by graup** [comment]
I succeeded a bit with adding the GenericRelation and querying based on the `related_name` I gave that. However, then it failed because my model's `pk` was an Integer, while `action_object_id` is a `CharField`.

I'll create a test project to showcase this problem.

**Comment by graup** [comment]
Here you are: https://github.com/graup/django-activity-stream-test

This also happens to reproduce #278.

**Comment by justquick** [comment]
@graup very helpful test project! been playing with it and in doing so i noticed a bug that is related to some other issues. unfortunately fixing it did not resolve this issue. 

This is the approach that makes the most sense to me but is still far away from working:

```python
# Version 1: Fails because of missing reverse relation
filters = {'action_object__read': False, 'action_object__deleted': False}
```

This is the solution that makes the least sense to me but is the closest to working:

```python
# Version 2: Fails because of not matching db column types
filters = {'notification__read': False, 'notification__deleted': False}
```

This is the query that is being performed in version 2:

```sql
SELECT "actstream_action"."id", 
       "actstream_action"."actor_content_type_id", 
       "actstream_action"."actor_object_id", 
       "actstream_action"."verb", 
       "actstream_action"."description", 
       "actstream_action"."target_content_type_id", 
       "actstream_action"."target_object_id", 
       "actstream_action"."action_object_content_type_id", 
       "actstream_action"."action_object_object_id", 
       "actstream_action"."timestamp", 
       "actstream_action"."public" 
FROM   "actstream_action" 
       INNER JOIN "example_notification" 
               ON ( "actstream_action"."action_object_object_id" = 
                    "example_notification"."id" 
                    AND ( "actstream_action"."action_object_content_type_id" = 9 
                        ) ) 
WHERE  ( "actstream_action"."actor_object_id" = 1 
         AND "actstream_action"."actor_content_type_id" = 4 
         AND "example_notification"."deleted" = false 
         AND "example_notification"."read" = false ) 
ORDER  BY "actstream_action"."timestamp" DESC 
```

Ive been trying to get a CAST stmt setup on the INNER JOIN to make the types comparable. In django you can use the `extra()` queryset operator but I cant get it working on a gfk lookup:

http://stackoverflow.com/questions/28101580/how-do-i-cast-char-to-integer-while-querying-in-django-orm

Unfortunately these joins on generic relations can get a bit messy. Im going to play around with it some more and hopefully get the approach that makes the most sense working in the best way.

**Comment by maguri** [comment]
Similar issue [here](https://github.com/justquick/django-activity-stream/issues/318).
Any idea?
