### ISSUE TITLE
Incorporate Django's message framework

### ISSUE THREAD

**Issue by avorio** [justquick/django-activity-stream#282]
What would be the best way to generate a Django framework message after someone follows something?

Do I have to re-implement the `follow()` method? That doesn't sound very efficient.

**Comment by justquick** [comment]
this is something you have to implement in your app using django signals. there is also a action signal in signals.py that you can handle. here's where you'd have to do it

http://django-activity-stream.readthedocs.org/en/latest/actions.html?highlight=signal

**Comment by avorio** [comment]
Hi @justquick, thanks for your response.

The problem is that the `request` is not available in that context, so I couldn't generate a Django framework message after someone follows something by relying on a `signal`.

Any thoughts on how to circumvent that?

**Comment by blag** [comment]
@avorio: [django-crequest](https://pypi.python.org/pypi/django-crequest/2014.9.19) is middleware that allows you to grab the current request from anywhere in your code - including signals.
