### ISSUE TITLE
The model User is not registered

### ISSUE THREAD

**Issue by YassWarrior** [justquick/django-activity-stream#285]
Hello,

I have this error when I want show activities stream.
Name application : main_app
My template : 

> ...
> {% load activity_tags %}
> 	{% activity_stream 'actor' user %}    
> 	{% for action in stream %}
> 		{% display_action action %}
> 	{% endfor %}
> ...

main_app/apps.py : 

> from django.apps import AppConfig
> 
> 
> class MainAppConfig(AppConfig):
> 	name = 'main_app'
> 
> def ready(self):
> 	    from actstream import registry
> 	    registry.register(self.get_model('User'))

If `from actstream import registry` is not in def ready, I have a other error : https://github.com/justquick/django-activity-stream/issues/279

And my settings.py :  

> INSTALLED_APPS = [
>     'django.contrib.admin',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.messages',
>     'django.contrib.staticfiles',
>     'django.contrib.humanize',
>     'django.contrib.sites',
>     'bootstrapform',
>     'main_app',
>     'actstream',
> ]
> 
> SITE_ID = 1
> 
> 
> MIDDLEWARE_CLASSES = [
>   ...

My signal (main_app/views.py):

> def my_handler(sender, instance, created, **kwargs):
>     action.send(instance, verb='was saved')
>     print("It's send ! ")  #It's works, I see it in the terminal.
> 
> post_save.connect(my_handler, sender=User) 

So the error is : 

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/project/main_app/views.py", line 165, in accueil
>     return render(request,"main_app/accueil.html",locals())
>   File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 67, in render
>     template_name, context, request=request, using=using)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 97, in render_to_string
>     return template.render(context, request)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 95, in render
>     return self.template.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 206, in render
>     return self._render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 197, in _render
>     return self.nodelist.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 173, in render
>     return compiled_parent._render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 197, in _render
>     return self.nodelist.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 69, in render
>     result = block.nodelist.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 326, in render
>     return nodelist.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 988, in render
>     bit = node.render_annotated(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 955, in render_annotated
>     return self.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/django/template/library.py", line 201, in render
>     output = self.func(*resolved_args, **resolved_kwargs)
>   File "/home/project/actstream/templatetags/activity_tags.py", line 198, in activity_stream
>     context[ctxvar] = getattr(Action.objects, stream_type)(*args, **kwargs)
>   File "/home/project/actstream/decorators.py", line 22, in wrapped
>     qs = func(manager, *args, **kwargs)
>   File "/home/project/actstream/managers.py", line 30, in actor
>     check(obj)
>   File "/home/project/actstream/registry.py", line 110, in check
>     'to register it.' % model_class.__name__)
> ImproperlyConfigured: The model User is not registered. Please use actstream.registry to register it.

Thank you

**Comment by jbsag** [comment]
I made a minimal example to try and reproduce your situation, but I couldn't. Since you aren't pointing to the `AppConfig` of  `main_app` in your `INSTALLED_APPS`, I am assuming you setting `default_app_config` in `main_app/__init__.py` ?

**Comment by YassWarrior** [comment]
Yes, it's my `main_app/__init__.py  ` :
 
`default_app_config = 'main_app.apps.MainAppConfig'`

**Comment by YassWarrior** [comment]
It's works !

I am very sorry, I didn't indent the code in  the `def ready(self):`.. 
Thank you !
