### ISSUE TITLE
jquery ajax follow/unfollow

### ISSUE THREAD

**Issue by spekzz** [justquick/django-activity-stream#286]
My frontend skills are limited, I have been trying to follow this [jsfiddle](http://jsfiddle.net/jakie8/ZECEN/) code with no luck, how would one get this to work without reloading the page using jquery ajax. Similar to [ProductHunt's](https://www.producthunt.com/medium) follow/unfollow button.

**HTML**

```
{% load activity_tags %}

<div class="follow-button">
  {% if request.user|is_following:object %}
    <a class="btn btn-primary" href="{% follow_url object %}">FOLLOWING</a>
  {% else %}
    <a class="btn btn-default" href="{% follow_url object %}">FOLLOW</a>
  {% endif %}
</div>
```

**Comment by justquick** [comment]
yea you can do the `$.ajax` method to hit `{% follow_url object %}` and toggle the button. an example project would b great and let me know if u make one or update the jsfiddle working w/ ajax support. i can add this to the docs but jquery is outside the scope of this project so i cant put it into the templates

**Comment by avorio** [comment]
This is interesting!

@northscope Did you manage to get this to work?

**Comment by aatishnn** [comment]
What about CSRF tokens? Wouldn't it introduce a CSRF issue?

**Comment by northscope** [comment]
@aatishnn You can use django ajax csrf code https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax

**Comment by aatishnn** [comment]
@spekz88 Since the follow/unfollow URLs are just GET requests, I was concerned about the CSRF issue. 

```
@login_required
@csrf_exempt
def follow_unfollow(request, content_type_id, object_id, do_follow=True, actor_only=True):
```
The view is CSRF exempted anyway and passing the CSRF code wouldn't do anything. I may be wrong though.

**Comment by spekz88** [comment]
@aatishnn your right, its just a GET request and the code wouldn't do anything, maybe overiding the `follow_unfollow` [views.py#L27](https://github.com/justquick/django-activity-stream/blob/master/actstream/views.py#L27) to a POST request?
