### ISSUE TITLE
Does django-activity-stream 0.6.0 support custom data?

### ISSUE THREAD

**Issue by wyx2000** [justquick/django-activity-stream#289]
it seems it should 0.4.4, but how come I don't see table column for it? and it sure doesn't work for me.
Any idea?

CREATE TABLE actstream_action
(
  id serial NOT NULL,
  actor_object_id character varying(255) NOT NULL,
  verb character varying(255) NOT NULL,
  description text,
  target_object_id character varying(255),
  action_object_object_id character varying(255),
  "timestamp" timestamp with time zone NOT NULL,
  public boolean NOT NULL,
  action_object_content_type_id integer,
  actor_content_type_id integer NOT NULL,
  target_content_type_id integer,

**Comment by justquick** [comment]
Make sure you set USE_JSONFIELD=True then migrate

http://django-activity-stream.readthedocs.io/en/latest/configuration.html#settings

**Comment by justquick** [comment]
http://django-activity-stream.readthedocs.io/en/latest/data.html
