### ISSUE TITLE
Monkey Patching DatabaseOperations::last_executed_query With No Checking of Django Version

### ISSUE THREAD

**Issue by fredpalmer** [justquick/django-activity-stream#299]
The comment here implies that patching won't take place depending on the version of Django:

https://github.com/justquick/django-activity-stream/blob/master/actstream/apps.py#L16

Well - there's absolutely no check for the version of Django and it does cause problems in some cases where the property on the `Cursor` object isn't set yet.  

Please remove this entirely.  It's really _not_ the responsibility of a 3rd-party application to patch Django in this regard.

**Comment by justquick** [comment]
yea i really didnt like this when i wrote it but the tests were failing on travis ci and this was the only way i could figure out how to fix it. i thought i just wrote it in the testapp but apparently not. this has gotta move

**Comment by justquick** [comment]
fixed in 22a21ca but waiting to see if the regressions pass

**Comment by justquick** [comment]
everything looks good. this error was so egregious that i made a hotfix release (0.6.3) which is now up on pypi

@fredpalmer thanks for the catch!
