### ISSUE TITLE
django.contrib.site need

### ISSUE THREAD

**Issue by missuor** [justquick/django-activity-stream#301]
Django 1.9.x 's been supported via doc(#supported-environments).

My env is Django1.9.7 and I  find that I must add 'django.contrib.site' into 'INSTALLED_APPS'. [Basic app configuration](http://django-activity-stream.readthedocs.io/en/latest/installation.html#basic-app-configuration) and do something like add site into my database(not do)

vim /path/to/envs/Lib/site-packages/actstream/feeds.py
and comment
`#from django.contrib.sites.models import Site # line 9`
and replace `Site.objects.get_current().domain` to `'/'`

please do update your doc or ?

**Comment by justquick** [comment]
no, the `...` should be wherever you put in your special sauce for your project. some projects dont need sites

**Comment by missuor** [comment]
![Image](https://github.com/user-attachments/assets/72142894-8f0d-4dd9-8fbc-5ab0fe966ccd)
