### ISSUE TITLE
Add git tag for version 0.6.2

### ISSUE THREAD

**Issue by jonemo** [justquick/django-activity-stream#302]
Just a small suggestion: Consider tagging the commit that got released to pypi as `0.6.2` with that version number. I just spent some time tracking down the bug reported in https://github.com/justquick/django-activity-stream/pull/266, not realizing that the fix has already been released. 

(I know, I shouldn't rely on Github tags for this, but tags are a convenient way to compare different release versions of a code base)

**Comment by justquick** [comment]
crap yea, i just forgot to make the release in github
