### ISSUE TITLE
No way to create a follower relationship from a custom user class?

### ISSUE THREAD

**Issue by shombo** [justquick/django-activity-stream#305]
Up front, I'm new to django and actstream, but not new to programming, etc. 

I am having a couple of issues here. The ideal solution would be to have a way to not have to rely on the django auth user class to create follower relationships. When trying to create a follower relationship with my custom user class, I get an error telling me that it must be of class User. 

I have attempted a work around where my user class can return a django user instance of itself and register a following relationship. This works for the creation of such relationships, but when I try to retrieve user_streams, it gives me an error saying that the model User isn't registered.

After going back to apps.py and playing with that for a bit, I cannot find a way to register the User class. With every different attempt to register such a class, I get an AppRegistryNotReady("Apps aren't loaded yet.") error.

`from django.contrib.auth.models import User`

is the cause of the error.

So my two main questions are this:
1. Is there any way whatsoever that I can use a different class other than User to establish a following relationship?
2. If not, how can I register the user class into the registry?

**Comment by justquick** [comment]
This app is most definately able to integrate with custom user models. Make sure you follow all these instructions first: https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#specifying-a-custom-user-model

it looks like from the error that you are trying to import the standard django user model but you should be importing your own model instead. also make sure that AUTH_USER_MODEL is set correctly in your settings.py. the code that handles the custom user model is all here https://github.com/justquick/django-activity-stream/blob/master/actstream/compat.py#L7
