### ISSUE TITLE
Setting to supply own Action class

### ISSUE THREAD

**Issue by stevelacey** [justquick/django-activity-stream#306]
I am on my second project where I've ended up wanting to muck with the Action class, and `contribute_to_class` only gets you so far.

An abstract class and option to override the default Action class that extends it would be ace.

Also UUID's would be good.

**Comment by justquick** [comment]
what would the migrations look like after you extend it?

what would uuids get you?

**Comment by stevelacey** [comment]
I don't really know, IIRC on the last project I'd generate them for actstream then move them into our project – and somehow it was manageable.

I expose Action over a DRF API, UUID's would make it consistent with everything else. I realised after suggesting this though that it gets a lot more problematic when you consider the foreign keys to Follow etc.

**Comment by justquick** [comment]
Im open to the idea, but may I ask what was the use case for you to have to subclass Action?

**Comment by stevelacey** [comment]
I just want UUID's right now – but I imagine I will want more – in the past, things like this:

- allow null actor (for persisting actions past the deletion of actors)
  
  ```
  Action._meta.get_field('actor_content_type').blank = True
  Action._meta.get_field('actor_content_type').null = True
  Action._meta.get_field('actor_object_id').blank = True
  Action._meta.get_field('actor_object_id').null = True
  ```
- custom `__str__`
- freeze `actor`/`action_object`/`target` `__str__` values on action (automatically in `__init__`)
  ```
  TextField(blank=True, null=True).contribute_to_class(Action, 'actor_string')
  TextField(blank=True, null=True).contribute_to_class(Action, 'action_object_string')
  TextField(blank=True, null=True).contribute_to_class(Action, 'target_string')
  ```
- link helpers
- long description helpers
- null object helpers for deleted users
  ```
  def user(self):
      return self.actor or get_model('accounts', 'User')(
          first_name=self.actor_first_name,
          last_name=self.actor_last_name,
          email=self.actor_email,
      )
  ```
- various additional fields and relations
  ```
  ForeignKey('accounts.Organization', related_name='organization_id', blank=True, null=True).contribute_to_class(Action, 'organization')
  ```

**Comment by justquick** [comment]
Some of those features sound useful so Im interested in looking into this but Ill have to think about it. Actions require actors by the design specification from http://activitystrea.ms/. I think a lot of what you are looking for can be modeled inside your own project by maintaining a FK to Actions.
