### ISSUE TITLE
User app required by activity stream breaks django

### ISSUE THREAD

**Issue by cmwaura** [justquick/django-activity-stream#315]
Is there a different way of registering the user model in Django>= 1.9.5.  This is because I am getting this error 

```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

and Initially i thought it was activity stream giving me problems but its actually django complaining due to the fact that i imported the user model i.e

```
from django.contrib.auth.models import User
```

in the apps.py. Everything else is working well except for that.

**Comment by cmwaura** [comment]
Figured it out, the problem was that you need to import the user model inside
    
    def ready():
        # import registry
        #import user model here

Anyway, I would like to help with the documentation of this project is the authors are willing.

**Comment by auvipy** [comment]
yes please send a pr

**Comment by cmwaura** [comment]
Thank you. I will do a write up this weekend since i worked and submit a pr.

**Comment by auvipy** [comment]
OK

**Comment by NogerbekNurzhan** [comment]
@cmwaura Hello! Can you say how exactly you solve your problem?

I tried to make as you said but I have that problem. What I miss?

**models.py**:
```
from actstream import registry

class Characterictic(models.Model):
    ...

registry.register(Characterictic)
```

**apps.py**:
```
from django.apps import AppConfig

class ProjectConfig(AppConfig):
    name = 'project'

    def ready(self):
        from actstream import registry
        from project.models import Characteristic
        registry.register(self.get_model(Characteristic))
```

**__init__.py**:
`default_app_config = 'project.apps.ProjectConfig'`

**Comment by cmwaura** [comment]
Oh yeah I did an open source project that uses the user model and has an accounts Profile app. Here is my registry

`
from django.apps import AppConfig,apps
import accounts
import newsfeed 
class NotesConfig(AppConfig):
    name = 'notes'

    def ready(self):
    	from actstream import registry
    	from django.contrib.auth.models import User

    	registry.register(self.get_model('NoteBook'))
    	registry.register(apps.get_model('newsfeed.NewsFeed'))
    	registry.register(apps.get_model('accounts.UserProfile'))
    	registry.register(User)`
