### ISSUE TITLE
Support follow type

### ISSUE THREAD

**Issue by zmrenwu** [justquick/django-activity-stream#317]
Now, **django-activity-stream** only support one follow type that is follow or unfollow. However, there are  other follow relationships such as *like*, *favorite*, *watch* and so on. So we need a type field in Follow model: `type =models.CharField()`. Thus, we can do some different things for different follow type. For example, if a user *favorite* a forum post, he/she would see all activity stream which target object is that post. We also allow user to *like* a forum post, but in this case, the activity stream would not show on user's feeds. *favorite* and *like* are all follow relationship but we should treat them differently.

The current app framework is easy to support it. Just add a type field in Follow model and extend the follow  and unfollow view that make them can receive a type parameter and use that mechanism to retrieve or create the Follow model.

**Comment by auvipy** [comment]
+1 could you make a PR with the proposed changes? what would be awesome

**Comment by zmrenwu** [comment]
@auvipy If the author agree with my proposal, I will do this. For now, I just use it in my project.

**Comment by auvipy** [comment]
I am a co maintainer of the project

**Comment by zmrenwu** [comment]
Great! I will try it.

**Comment by zmrenwu** [comment]
@auvipy Sorry, but is there any contributor instruction or developer guides? I can not find any information from the official docs. Which branch should I start with? And how do I make the PR if I done the work(Create a new feature branch?). Forgive me, I am not experienced in open source project.

**Comment by auvipy** [comment]
master is the default branch :)

**Comment by auvipy** [comment]
merged on master.
