### ISSUE TITLE
Filter Action Error:  Field 'actor' does not generate an automatic  reverse relation and therefore cannot be used for reverse querying. 

### ISSUE THREAD

**Issue by maguri** [justquick/django-activity-stream#318]
Hey every one (@justquick),

I have a django app and now I want to introduce **django-activity-stream** to notify users from events.

My **issue** is that I can not `filter` actions by `actor` or `target`:

> `python3.5 shell`
```
>>> from app import models
>>> a = models.MyAppUser.objects.all()[1]
>>> a
<MyAppUser: Mark>
>>> t = models.MyAppUser.objects.all()[2]
>>> t
<MyAppUser: Steve>
>>> from actstream.models import Action
>>> Action(actor=a, verb='POST', target=t)
<Action: Mark POST Steve 0 minutes ago>
>>> Action.objects.filter(actor=a)
```

> **Error**:
```
Traceback (most recent call last):
  File "/.../lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/.../lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/.../lib/python3.5/site-packages/django/db/models/query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/.../lib/python3.5/site-packages/django/db/models/query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/.../lib/python3.5/site-packages/django/db/models/sql/query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/.../lib/python3.5/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/.../lib/python3.5/site-packages/django/db/models/sql/query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/.../lib/python3.5/site-packages/django/db/models/sql/query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/.../lib/python3.5/site-packages/django/db/models/sql/query.py", line 1316, in names_to_path
    "adding a GenericRelation." % name
```
```
django.core.exceptions.FieldError: Field 'actor' does not generate an automatic 
reverse relation and therefore cannot be used for reverse querying. 
If it is a GenericForeignKey, consider adding a GenericRelation.
```
The output of my `pip freeze` is:

```
app==0.0.1
coverage==4.2
dj-database-url==0.4.1
**Django==1.9.5**
**django-activity-stream==0.6.3**
django-anymail==0.5
django-bootstrap-breadcrumbs==0.8
django-bootstrap-datepicker==1.1.1
django-bootstrap3==7.1.0
django-bower==5.1.0
django-configurations==2.0
django-debug-toolbar==1.5
django-formtools==1.0
django-nose==1.4.4
django-postman==3.3.2
factory-boy==2.7.0
fake-factory==0.7.2
flake8==3.0.4
mccabe==0.5.2
nose==1.3.7
Pillow==3.3.1
psycopg2==2.6.2
pycodestyle==2.0.0
pyflakes==1.2.3
python-dateutil==2.6.0
PyYAML==3.12
requests==2.11.1
rollbar==0.13.6
six==1.10.0
sqlparse==0.2.1
whitenoise==3.2.1

```

Similar like [issue 281](https://github.com/justquick/django-activity-stream/issues/281)

**Comment by maguri** [comment]
`actor_stream(a)`

**Comment by Q-bart** [comment]
?

**Comment by akshay-soni** [comment]
This could work - 
Action.objects.filter(actor_object_id__in=user_queryset.values_list('id', flat=True))

**Comment by abubakarA-Dot** [comment]
Hi, @justquick I am trying to display an activity stream when a user sends a network request to a certain user. when I filter a user on the basis of actor or target it says: "Field 'actor' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation."
I have applied the solutions provided in this issue but couldn't display the correct activity stream. Can you help me with that?
My CODE example:

        current_user = User.objects.get(id =request.user.id)

        network = AddToNetwork.objects.filter(network_status = 'ADD')


        actor = Action.objects.filter(actor=current_user, target=network)

**Comment by abubakarA-Dot** [comment]
![image](https://user-images.githubusercontent.com/59768644/184526847-1bcf799c-47bd-4267-99b5-adcae6f18ea4.png)

when I perform action.send activity, it generates 2 ids but it should only generate 1 activity at the same time.
special thing or bug is that, it generates two opposite features in a single API hit. for instance, I want to send a friend request to user and user( who is sending the request(actor)) email is abc@gmail.com and the target's email is target@gmail.com, what it is doing right now is, it says, abc@gmail.com sent you a network request target@gmail.com 1 minute ago, and it also says target@gmail.com sent you a friend request. it is a kind of bug or I am doing something wrong. I just want to get a result something like this: actor@gmail.com sent you a network request target@gmail.com

**Comment by abubakarA-Dot** [comment]
> ![image](https://user-images.githubusercontent.com/59768644/184526847-1bcf799c-47bd-4267-99b5-adcae6f18ea4.png)
> 
> when I perform action.send activity, it generates 2 ids but it should only generate 1 activity at the same time. special thing or bug is that, it generates two opposite features in a single API hit. for instance, I want to send a friend request to user and user( who is sending the request(actor)) email is [abc@gmail.com](mailto:abc@gmail.com) and the target's email is [target@gmail.com](mailto:target@gmail.com), what it is doing right now is, it says, [abc@gmail.com](mailto:abc@gmail.com) sent you a network request [target@gmail.com](mailto:target@gmail.com) 1 minute ago, and it also says [target@gmail.com](mailto:target@gmail.com) sent you a friend request. it is a kind of bug or I am doing something wrong. I just want to get a result something like this: [actor@gmail.com](mailto:actor@gmail.com) sent you a network request [target@gmail.com](mailto:target@gmail.com)

in this photo, when I accept a request, it says, marr accepted your request. but it also says, marry sent you a request. so where I am doing something wrong? @justquick

**Comment by abubakarA-Dot** [comment]
@justquick I am looking for help. I hope you can help me.
NOTE: I have Django version 4.0.x and Python version 3.9.10

**Comment by justquick** [comment]
the app doesnt create any actions like those above. they must be sent in your project using the app's signal. id try looking where you are sending the signals and see what arguments ur sending. it seems the actor is the same in both actions which i dont think is right

**Comment by abubakarA-Dot** [comment]
yes. you are right. I am using signals in my app using a custom User model. so let me send you the code examples that I have implemented. I am sure, I have faulty code.

**Comment by abubakarA-Dot** [comment]
my signals.py:
```
def my_handler(sender, instance, created, **kwargs):
    action.send(instance, verb='sent you a network request')

post_save.connect(my_handler, sender=AddToNetwork)
```

my apps.py:

```
from django.apps import AppConfig, apps


class DatastructureConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'datastructure'

    def ready(self):
        from actstream import registry
        registry.register(self.get_model('User'))
        registry.register(apps.get_model('datastructure.AddToNetwork'))
```

my views.py logic:
```

add_to = User.objects.get(id = id)
        current_user = User.objects.get(id = request.user.id)
        network = AddToNetwork.objects.create(add_to = add_to, added_from=current_user,network_status = 'ADD')

        # it is representing django-action-stream it will display the message on front end
        action.send(current_user, verb='sent you a network request', target=add_to)
```

NOTE: I want to display the information only to that user, who got the network request. no other user should see that message. Like, if I have sent you a network request, it should Say Abubakar sent you a network request. and if you have accepted the network request, it will be displayed on my profile something like this, JustQuick has accepted your network request.

I know it is the logic that I have to implement but I have no relation to the activity stream with my project models so I am not sure how to display the user-related information.
Your help is highly appreciated because I am stuck on this issue for almost 5 days now.

**Comment by abubakarA-Dot** [comment]
I have realized that the second instance is being created from signals.

**Comment by abubakarA-Dot** [comment]
when I try to implement this logic to display the activity stream on the home/user dashboard page:
        ```
current_user = User.objects.get(id =request.user.id)
        network = AddToNetwork.objects.filter(network_status = 'ADD')

        actions = Action.objects.filter(verb='sent you a network request', actor=current_user, target=network)
        print("\n Actor message :", actions)
```
it throws the following error:

Field 'actor' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.

**Comment by abubakarA-Dot** [comment]
@justquick I am sure, I have explained things smoothly so that you can understand my problem.
