### ISSUE TITLE
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'

### ISSUE THREAD

**Issue by nikparmar** [justquick/django-activity-stream#322]
When accessing the `/activity/` url getting this error.
May be the code base is yet not compatible with the django 1.10

**Comment by cmwaura** [comment]
yeah i am fixing this error and hopefully my pr should be accepted

**Comment by auvipy** [comment]
try the code from master

**Comment by cmwaura** [comment]
hey @auvipy  i tried the code from the master but i think django 1.10 the context_instance variable in render_to_response, so most of the views using it fail in django 1.10. I submitted a PR. Let me know what you think.

**Comment by auvipy** [comment]
yes I put a comment there too
