### ISSUE TITLE
ImportError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by raymestalez** [justquick/django-activity-stream#323]
Hi! I have just installed this app with:
`pip3.5 install django-activity-stream
`
 added it to my INSTALLED_APPS, and added this to urls.py:

`('^activity/', actstream.urls),`

When I'm trying to run my project, I'm getting an error:

`ImportError: No module named 'django.core.urlresolvers'`

Am I doing something wrong?

(I'm using Django 2.0, if it matters)

**Comment by raymestalez** [comment]
Swithed to Django 1.10.5, now the error goes:

`No module named 'django.conf.urls.defaults'`

**Comment by nikparmar** [comment]
I had to go back into the code and update this line with `django.conf.urls`

**Comment by raymestalez** [comment]
Awesome, thank you! The issue was with the file urls.py, which tried to import patterns from django.conf.urls, and this is deprecated in django 1.10, so that triggered the input error.

Anyways, apparently this issue was already fixed, I've just had an older version of this app installed from pip. Installing the most recent code from github with:
`pip3.5 install git+https://github.com/justquick/django-activity-stream.git#egg=actstream`
solved the problem.

This error is gone now.

**Comment by NogerbekNurzhan** [comment]
Hello @raymestalez How exactly you solve your problem? I have the same error. What exactly you changed in actstream\urls.py?

**Comment by auvipy** [comment]
update your codes
