### ISSUE TITLE
Can I use this app to implement ActivityPub?

### ISSUE THREAD

**Issue by raymestalez** [justquick/django-activity-stream#324]
Hi! I am trying to figure out how to implement [ActivityPub](https://www.w3.org/TR/activitypub/) protocol on my website. I have never done this before, so I don't entirely understand how these things work. 

Do you think I will be able to use this app to implement this protocol? Can you give me some advice on how I should go about doing that?

**Comment by cmwaura** [comment]
yeah you can use this to implement it. I did a project called django-social-site which uses activity stream to create what you are looking for. 

cheers

**Comment by morenoh149** [comment]
@raymestalez if your issue is solved please close.
