### ISSUE TITLE
How can I generate a json feed of my posts?

### ISSUE THREAD

**Issue by raymestalez** [justquick/django-activity-stream#325]
Hi! I have a blog-type website, and I want to generate json feed of the activity stream of my latest posts. I want to be able to go to /feed/posts/, and see my latest posts in a json format.

I've been reading the [docs](http://django-activity-stream.readthedocs.io/en/latest/feeds.html), but it is still unclear. I don't understand how can I generate a feed for a specific model, and then point a specific url to it. 

Ideally, I would just create a view where I take the list of activities, convert them into a json format, and then return this json.

Can you give me an example of how it's done?

**Comment by auvipy** [comment]
use django rest framework for json response
