### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by suriya** [justquick/django-activity-stream#335]
There have been a lot of changes since the last release. Could you please release a new version with the latest commits?

**Comment by auvipy** [comment]
I think waiting a week should be sensible time.

**Comment by pmn** [comment]
Also being bitten by the [url includes issue](https://github.com/justquick/django-activity-stream/issues/323) in Django 1.10. Being able to normally pip install this dep (vs. a specific commit) would be 🥇 .

**Comment by auvipy** [comment]
that will be resolved soon :package:

**Comment by ckoehn** [comment]
Any plans to release a new version soon?

**Comment by MiiRaGe** [comment]
When is the new version coming out ? =)

**Comment by justquick** [comment]
Updated release
