### ISSUE TITLE
Receiving Invalid block tag: 'activity_mystream'

### ISSUE THREAD

**Issue by Khailz** [justquick/django-activity-stream#337]
I am getting `Invalid block tag on line 828: activity_mystream. Did you forget to register or load this tag?` I have reinstalled and uninstalled several times. Changing the name of  the `{% load activity_tags %}` tag, it is listed under acceptable tags. It worked fine before, is this just an issue with django 1.10?

**Comment by robinsandstrom** [comment]
Can you post your settings.py? Are you sure that you have included actstream in settings and urls?

My installation started to bug when I deployed to heroku, and for some reason it was raising import errors from a previous version of django-activity-stream that was later fixed. Anyways, I fixed it by forking the repo and installing the forked repo instead.

**Comment by Khailz** [comment]
My Settings are 

`INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'actstream',
    'community',
    'crispy_forms',
    'friendship',
    'tagging',
    'django_comments',
    'rest_framework',
    'stream_django',
    'mptt',
    'notifications',
    'el_pagination',
    'account'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'unlighted.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
#                 'django.core.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'unlighted.wsgi.application'

AUTH_USER_MODEL = 'community.AuthUser'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
CRISPY_TEMPLATE_PACK = 'bootstrap3'
ACTSTREAM_SETTINGS = {
    'MANAGER': 'community.managers.MyActionManager',
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': True,
    'GFK_FETCH_DEPTH': 1,
}`
The url
`url('^activity/', include('actstream.urls')),` is also there, this is not a new installation.

**Comment by auvipy** [comment]
could you try this against master branch?

**Comment by Khailz** [comment]
I've tried that along with your fork

**Comment by auvipy** [comment]
@robinsandstrom could you send a PR for this fix from your fork?

**Comment by Khailz** [comment]
I've tried a lot now and still can't get it working, is it just no compatible with python 3.5?

**Comment by auvipy** [comment]
did you loaded the template tag properly?

**Comment by Khailz** [comment]
Its in my Installed apps if thats what you mean
