### ISSUE TITLE
actor seems to be `None` when accessing the feed or streams.

### ISSUE THREAD

**Issue by annshress** [justquick/django-activity-stream#340]
### select * from actstream_follow;
 id | object_id | actor_only |             started              | content_type_id | user_id 
----+-----------+------------+----------------------------------+-----------------+---------
  6 | 4         | f          | 2017-03-23 16:57:45.890132+05:45 |              56 |     203
(1 row)

### select * from actstream_action;
id | actor_object_id |      verb       | description | target_object_id | action_object_object_id |            timestamp             | public | data | action_object_content_type_id | actor_content_type_id | target_content_type_id 
----+-----------------+-----------------+-------------+------------------+-------------------------+----------------------------------+--------+------+-------------------------------+-----------------------+------------------------
 19 | 4               | added new offer |             | 6                |                         | 2017-03-23 17:13:56.419528+05:45 | t      |      |                               |                    56 |                     53
 20 | 4               | added new offer |             | 2                |                         | 2017-03-26 10:10:59.1976+05:45   | t      |      |                               |                    56 |                     53
(2 rows)

The action and follow model contain exact information.

But, now when I look up in the url `/activity/feed/json`

AttributeError at /activity/feed/json/
'NoneType' object has no attribute '_meta'

So, the actor object was actually None.

In [13]: any_stream(b)
Out[13]: <QuerySet [<Action: None added new offer bumper upahaar 29 minutes ago>, <Action: None added new offer new offer 2 days, 17 hours ago>]>

BUT...
In [14]: Action.objects.all()
Out[14]: <QuerySet [<Action: This That Mall (Nepal) added new offer bumper upahaar 30 minutes ago>, <Action: This That Mall (Nepal) added new offer new offer 2 days, 17 hours ago>]>

**Comment by annshress** [comment]
![prefetch1](https://cloud.githubusercontent.com/assets/6479061/24329156/1a4bd0f2-121d-11e7-821e-22b18bf2d1b7.png)

![prefetch2](https://cloud.githubusercontent.com/assets/6479061/24329158/1f22c6a8-121d-11e7-9ec4-ad9c42791e8a.png)

So, the problem arose from `Queryset.prefetch_related(*lookups)`. The (_so what simple looking function_) `extend` seems to be modifying the queryset. Was it supposed to happen?

From [documentation](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#prefetch-related) : 
> For example, prefetching objects referenced by a GenericForeignKey is only supported if the query is restricted to one ContentType.

But our queryset contains objects of different ContentTypes?

**Comment by annshress** [comment]
So, this issue was related to model inheritance. 
Say,

```python
class A(models.Model):
    pass
```

```python
class B(A):
    arbitray_field = a_field()
```

Now, creating actions from `Model A` seems to be working fine, and getting streams at the _prefetch__related_ is working okay. 

But creating actions from `Model B` seems to be changing the _object of B_ to None.

**Comment by justquick** [comment]
can you please post a complete working example (preferably as a unittest) of the issue you are seeing?
