### ISSUE TITLE
Marking notification as read by user

### ISSUE THREAD

**Issue by cypreess** [justquick/django-activity-stream#341]
I did not spot such functionality in docs. Is there a chance to mark specific notifications as read? This would be super helpful.

**Comment by auvipy** [comment]
isn't it well suited to be done with any javascript?

**Comment by cypreess** [comment]
@auvipy what do you meant by that? By remembering on JS side that some notification were seen? Then it would not survive page refresh.

**Comment by cawjustin** [comment]
You need a separate model for tracking action reads. It's something we also need to do.

But it would be great as a native feature of actstream.

**Comment by auvipy** [comment]
do you plan to implement it in activity stream or use django notifications package with actstream?

**Comment by raphaelyancey** [comment]
Any progress on this functionality? Would love to use it too.

**Comment by raphaelyancey** [comment]
Figured out a workaround by storing the last time the user visited its notifications. New notifications are the notifications which `timestamp` is greater than the stored value.

```python
# Wherever you want to display the unread notifications count
@register.simple_tag(takes_context=True)
def unread_notifications_count(context):
    user = context['user']
    if user.is_anonymous():
        return 0
    else:
        latest_read = user.forum_user.notifications_read_until
        new_notifications = Action.objects.user(user).filter(timestamp__gte=latest_read)
        return len(new_notifications)
```

```python
# Wherever the notifications are fetched at the user's request
fu = user.forum_user
fu.notifications_read_until = datetime.now()
fu.save()
```
