### ISSUE TITLE
Django 1.11 Incompatibilities

### ISSUE THREAD

**Issue by cb109** [justquick/django-activity-stream#342]
The overall functionality to store actions via signals seems to work nicely in Django 1.11, but trying to use the `activity_stream` and `display_action` templatetags I came across some small things that are broken due to changes in 1.11.

* `actstream/templatetags/activity_tags.py`, line 96:
    ```python
    return render_to_string(templates, context)
    ```
    Context is a `django.template.context.Context` instance here, but in 1.11 it must be a simple dict,
    ```python
    return render_to_string(templates, context.flatten())
    ```
    would possibly fix that, haven't fully tested it yet.

* `actstream/urls.py`, top of the file:
    ```python
    try:
        from django.conf.urls import url, patterns
    except ImportError:
        from django.conf.urls.defaults import url, patterns
    ```
    The `patterns()` function is not available anymore, either the url patterns need some rework or you'd have to provide your own vendorized version. In 1.9 it says: 
    > django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.

* `actstream/views.py`: All usage of `render_to_response()` is a problem, see https://docs.djangoproject.com/en/1.11/releases/1.10/
    > The dictionary and context_instance parameters for the following functions are removed:
django.shortcuts.render()
django.shortcuts.render_to_response()

The changelog tells me that the latest, officially supported Django version is 1.9. Are there any plans yet to extend support to Django 1.10+?

**Comment by cb109** [comment]
@auvipy @cmwaura As far as I see you are working on related stuff on the `auvipy-patch-1` branch?

**Comment by cmwaura** [comment]
Hey there, 

I was working on the branch and the views section should be working for django >1.9. I changed the render_to_response() to render and even though the context_instance argument was deprecated, it still accepts the context argument as a dict. I will look through some of the other problems that you may have mentioned this weekend and will submit a PR soon (if needed)

Cheers

**Comment by cb109** [comment]
Thanks for your response @cmwaura, that sounds good. We are planning to use actstream in our project, but are on Django 1.11 as mentioned before. It seems this project has a great testing setup, maybe we can introduce support for that without too much hassle.

You are very welcome to open a PR to move this forward, I'd love to contribute fixes to get this done.

**Comment by auvipy** [comment]
you can ryn the tests against 1.11.1 and fix them one by one my prvious work was staled due to my laptops demage. https://github.com/justquick/django-activity-stream/pull/334  i could resume the work next week if no one beat me

**Comment by dezoito** [comment]
> #334 i could resume the work next week if no one beat me

Please do! ;)

**Comment by rrmerugu** [comment]
whats the status of this PR? Eagerly waiting for 1.11 support

**Comment by cmwaura** [comment]
@auvipy  are you on this or should i get on this now that the weekend is almost here?

**Comment by auvipy** [comment]
please take over my pr and mention me when you are done. I am too busy with @celery project

**Comment by cmwaura** [comment]
alright will do

**Comment by muminoff** [comment]
Is it not fixed yet? Still no support for Django 1.11?

**Comment by subho007** [comment]
Any updates on this @cmwaura ? can I help in some way to expedite this ?

**Comment by cmwaura** [comment]
@subho007 working on it right now.. Sorry work got me really busy.

**Comment by cmwaura** [comment]
@subho007 @auvipy it seems like the codebase was fixed but the fixes live within github.. am looking at the latest code and it looks fixed. Am I missing something?

**Comment by cmwaura** [comment]
@subho007 @auvipy it seems like the codebase was fixed but the fixes live within github.. am looking at the latest code and it looks fixed. Am I missing something?

**Comment by dezoito** [comment]
Well, the version still says 0.6.3 and there's no mention of compatibility with Django 1.11...

**Comment by cmwaura** [comment]
@dezoito I updated my project to django> 1.11 and updated the activity streams to the latest version and everything seems to be working correctly. Please message me and let me know what deprecation warnings you are receiving and where.

**Comment by muminoff** [comment]
@cmwaura I have been waiting Django 1.11 support for long, after your confirmation, I have tried.

This is what I got:

```python
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/sardor/Projects/incogwas/igsite/incogwas/urls/__init__.py", line 14, in <module>
    url(r'activity/', include('actstream.urls')),
  File "/Users/sardor/.virtualenvs/incogwas/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/sardor/.virtualenvs/incogwas/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/sardor/.virtualenvs/incogwas/lib/python3.6/site-packages/actstream/urls.py", line 5, in <module>
    from django.conf.urls.defaults import url, patterns
ModuleNotFoundError: No module named 'django.conf.urls.defaults'
```

System information:
```bash
$ python --version
Python 3.6.0
$ python -c 'import django; print(django.__version__)'
1.11
$ python -c 'import actstream; print(actstream.__version__)'
0.6.3
```

**Comment by cmwaura** [comment]
@muminoff  but have you tried the git repository version. I fixed this problem sometime back and it got accepted in the repo. What i am assuming is that they didn't update the version number after i pushed the fixes. Also they may have forgotten to push it to pypi that is, if it is not done automatically.

Check this link out 

https://github.com/justquick/django-activity-stream/blob/master/actstream/urls.py

The problem python/django is complaining about is not there i.e line 5

**Comment by muminoff** [comment]
@cmwaura I am waiting for PIP release. I have been already using git version.

**Comment by cmwaura** [comment]
@muminoff sorry i dont have access to that you will need to message the core developers or @auvipy for him to update the pip version

**Comment by muminoff** [comment]
@cmwaura the repo has already got more than 1k stars, and it means people are using the project, if core developers cannot maintain, they must describe in readme that they decided to abandon the project instead of keeping the issue open or not accepting the PRs

**Comment by cmwaura** [comment]
@muminoff I understand your frustrations but for me there's nothing more I can do. I took upon myself to help out as much as I can since I caught the problems earlier on, but now the rest goes to the core developers.

**Comment by dezoito** [comment]
@cmwaura , Thank you for the effort!
I just got it working (installed it from the repo), after a few minor tweaks.

Hope @justquick or @auvipy can bump the version number and have this officially on PIP.

**Comment by cb109** [comment]
Thanks for your work @cmwaura :bow:

**Comment by jeasoft** [comment]
Still waiting for the official PIP version supporting Django 1.11. Thanks @cmwaura @auvipy @justquick for your work with this library

**Comment by arski** [comment]
@cmwaura just to understand correctly, youre saying the latest master of the official repo supports 1.11, or even the latest tagged version? Did you raise any PRs to fix any 1.11 incompatibilities? Would be nice to see here.

Thanks! Wasn't quite clear on the status from this thread

**Comment by auvipy** [comment]
could you guys verify if master is working properly with django 1.11.x? if not please raise issues here. I will try to collaborate with @justquick to make a new release soon if master is working well

**Comment by cmwaura** [comment]
@auvipy if no one does i will this weekend

**Comment by auvipy** [comment]
please check this https://github.com/justquick/django-activity-stream/releases/tag/0.6.5 and report issues,

travis seems to be green and I have mailed @justquick for a pypi release, next step will be working to add djanfo 2.0 full compat

**Comment by arski** [comment]
! Great news, thanks for this!

**Comment by siovene** [comment]
I'm having some trouble with django-activity-stream on Django 1.11. In my action template (`myapp/templates/actstream/action.html`) I need the `request` object but that's missing because `activity_tags.py` omits the `request` when calling `render_to_string` in `class DisplayAction`.

Am I missing something?
