### ISSUE TITLE
Can't display target or action_object with {% activity_stream %}

### ISSUE THREAD

**Issue by fmatray** [justquick/django-activity-stream#349]
Hello,
I can't display all informations when I use `{% activity_stream %}`. 
** Result with the template** 
I want to display the action_object also
```
admin created 9 heures, 28 minutes ago 
admin saved 9 heures, 49 minutes ago 
[..]
```
**instead of** 
```
admin created A short story of Love 9 heures, 28 minutes ago 
[..]
```

**settings**
```
ACTSTREAM_SETTINGS = {
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': False
}

```
**models.py**
```class ShortStory(TextBase):
    content = RichTextField(_("Content"), blank=True)
```
**signals.py**
```
@receiver(post_save, sender=ShortStory)
def shortstory_handler(sender, instance, created, **kwargs):
    verb = ("updated", "created")[created]
    action.send(instance.created_by, verb=verb, action_object=instance)
```

**Template (I tried with stream any also)**
```
      {% activity_stream 'model' Text_object %}
      {% for action in stream %}
          {% display_action action %}<br>
      {% endfor %}
```

**Result in detail view**
http://127.0.0.1:8000/fr/activity/detail/25/
```
admin created A short story of Love a 10 heures, 32 minutes ago
On 23 août 2017 at 00:39
```
In my DB this is the action
id,actor_object_id,verb,description,target_object_id,action_object_object_id,timestamp,public,action_object_content_type_id,actor_content_type_id,target_content_type_id
25,1,created,,,1,2017-08-22 22:39:17.622760,1,59,5,

I tried several things but without any result.
Can you help me please ?

**Comment by justquick** [comment]
try overriding the [display action template](https://github.com/justquick/django-activity-stream/blob/master/actstream/templates/actstream/action.html). you can change one of the following in your projects' templates

```
actstream/<verb>/action.html
actstream/action.html
```
