### ISSUE TITLE
when one to one field is set as primary key, stream decorator removes item as target

### ISSUE THREAD

**Issue by KeynesYouDigIt** [justquick/django-activity-stream#353]
im using actstream to populate a stream with things like

`guy posted whats up on group_feed`
 
My issue is, for a certain type of `group_feed`, the `group` object has been changed to have this

`org = models.OneToOneField(Organization, primary_key=True)`

(this was done since devs were complaining that the org id should have the same PK as the org_feed)

Now when the @ stream decorator runs `fetch_generic_relations()` it cant find the generic relation and pops out as 
`guy posted whats up` (note the missing feed)

ive confirmed this is only happening for feeds attached to an object with a onetoone field and primary key=true .

Whats even *stranger* is when I make a custom @ stream decorator to run `fetch_generic_relations('')`

everything runs fine. It doesnt appear if any of the if statements in stream are hitting true.

How is `fetch_generic_relations()` supposed to work? I keep reading through it and nothing seems to stick out to me as to where the gfk gets screwed up. Help?

**Comment by KeynesYouDigIt** [comment]
Ive confirmed that this function is the problem

```
        print(qs.fetch_generic_relations('').first().target_object_id)
       #outputs a pk number
        print(qs.fetch_generic_relations().first().target_object_id)
      #outputs nothing
```

when they are literally right next to each other in the @ stream function

**Comment by KeynesYouDigIt** [comment]
So the argument appears to be nullifying the funtions steps... but where in this function is the target_object_id being obliterated when there is no arg??

**Comment by KeynesYouDigIt** [comment]
@justquick Was the error not explained properly?

**Comment by slurms** [comment]
👋 hi @KeynesYouDigIt -- turns out the "fix" for this at the moment is to do this in your `settings.py`:

```
ACTSTREAM_SETTINGS = {
    # yada yada
    'FETCH_RELATIONS': False,
}
```

it's more than likely an issue with Django's prefetch_related itself, not django-activity-stream. However, that means we lose the query optimisation in prefetching content objects (actor, action_object, and target).
