### ISSUE TITLE
[Question] use small integer for verbs?

### ISSUE THREAD

**Issue by ralphite** [justquick/django-activity-stream#354]
For better performance could you change to small integer with choices for verb?

**Comment by auvipy** [comment]
how much performance gain that would add? changing field type will create backward incompatibility issue. how you plan to handle that?

You are welcome to send a patch with proposed changes. ping me with the PR

**Comment by justquick** [comment]
good idea, i normally do that to my models when I have a _determined_ set of fields to choose from. it helps keep down the db storage footprint as well as aids in indexing. the problem w/ verbs is that I wanted to leave them open for more flexible user input. if someone wanted to add a new verb like 'slept' then I dont want them to have to roll out a code deployment to add it to a choices list. im leaving the flexibility up to the project that implements this app
