### ISSUE TITLE
django 2.0.x support and drop versions reaching EOL

### ISSUE THREAD

**Issue by auvipy** [justquick/django-activity-stream#355]

**Comment by asdfkaba** [comment]
I faced some other Problems with Django2, which i fixed here:
https://github.com/asdfkaba/django-activity-stream/commit/2b1f13736a5cfb37d84e39a4c8e20b5f6097545d

I don't know if i did that correct, my fix for the queryset._clone  is inspired from:
https://github.com/jazzband/django-model-utils/commit/a07140e77165b6e9becef76c4a8609209ace545d#diff-a4a84bac70b6f91df5344a194dbe270a

**Comment by C4ptainCrunch** [comment]
Do you have any news on this ? It would be nice to have an ETA so we can plan our own migration to Django 2.0 :)

**Comment by auvipy** [comment]
If you check the master commits I have fixed many django 1.11/2.0 errors, now you could try the master branch localy and report which errors you are facing

**Comment by auvipy** [comment]
c6daba02cafad522c12bdbe2828d1e0cf8df78bd 1b25e992e68009cf39e4ebcf16976bbd2300e012

**Comment by slurms** [comment]
Seems to be working fine for me locally. 👍

**Comment by auvipy** [comment]
some works needed to update the tests though :D to make the travis green again! if anyone could check the errors and tell me the fix i will be happily able to implement the code changes :+1:

**Comment by auvipy** [comment]
fixed on master
