### ISSUE TITLE
display_action, render_to_string and context isolation

### ISSUE THREAD

**Issue by fabrixxm** [justquick/django-activity-stream#357]
commit 1cd38f2a replace the context with a fresh dict.

I think it's related to #328 and #342 (I can't find more details about the change)

Problem is, that change isolates completely the action template from the context it will be inserted.

A quick example: I want to show the actor name as "You" if the actor is same as logged in user. I don't have the original context anymore, I can't access request.user...

**Comment by auvipy** [comment]
@justquick whats your opinion?

**Comment by hamstap85** [comment]
I too have this problem.
