### ISSUE TITLE
Django 2.0 Incompatibilities

### ISSUE THREAD

**Issue by guilhermej** [justquick/django-activity-stream#361]
Django 2.0 was released. The first problema that I face was a deprecated module:
django.core.urlresolvers. now it is django.urls

There is a prevision to give Django 2 suport?

**Comment by auvipy** [comment]
https://github.com/justquick/django-activity-stream/issues/355 is the issue to track the support work

**Comment by wolvesproduction** [comment]
I'd like to know how to update this package. I already fix this bug 

# Django 2.0 update -- django.core.urlresolvers has been deprecated
try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse

**Comment by niknokseyer** [comment]
@wolvesproduction can you create a pull request?

**Comment by auvipy** [comment]
masters is now all green and 2.0 should be fully supported
