### ISSUE TITLE
Recent release mismatch: 0.6.4 and 0.6.5

### ISSUE THREAD

**Issue by cjerdonek** [justquick/django-activity-stream#367]
On PyPI, the latest release is 0.6.4 uploaded on 2017-07-23:
https://pypi.python.org/pypi/django-activity-stream

However, the GitHub project doesn't show a 0.6.4 release, so it's not clear what SHA 0.6.4 on PyPI corresponds to:
https://github.com/justquick/django-activity-stream/releases

Also, GitHub shows a 0.6.5 release from December 2017 that isn't on PyPI, so it's also a little confusing as to how these two releases relate to each other. For example, is 0.6.4 on PyPI supposed to be the same as 0.6.5 on GitHub? That would explain why each is only released on one and not the other.

**Comment by auvipy** [comment]
Because the creator of the package is so busy

**Comment by cjerdonek** [comment]
Do you or anyone know the answers to these questions?

1. Are 0.6.4 and 0.6.5 different or the same?
2. If different, what's the SHA of 0.6.4?

**Comment by auvipy** [comment]
actually there is still no 6.5 release yet in pypi

**Comment by auvipy** [comment]
released https://pypi.python.org/pypi/django-activity-stream

**Comment by cjerdonek** [comment]
There is another issue I mentioned above that hasn't been addressed yet. Namely, there is no 0.6.4 release on GitHub tagging the 0.6.4 PyPI release. In particular, what is the SHA of the 0.6.4 PyPI release?

**Comment by auvipy** [comment]
@justquick if you could answer
