### ISSUE TITLE
Newsfeed New Pattern Issue

### ISSUE THREAD

**Issue by bobozar** [justquick/django-activity-stream#377]
I have a model called 'POSTNEWS' and it has been registered with actstream alongside USER model. I want to achieve the same or similar newsfeed pattern like Twitter.

I created a template that shows all item in 'POSTNEWS', so when a user visits url '/timeline/', all items in 'POSTNEWS' model will be displayed in template 'allnews.html'.

Now, I want this-  when a user lets call the user 'Jack', visits /timeline/, he should only see his items and items of people he is following and items of people who are following him.

Can I achieve this process with this package? I read through the docs but I'm yet to understand or know how to go about this.

**Comment by auvipy** [comment]
yes you should. to get more faster response for your support queries post on the gitter chat channel first
