### ISSUE TITLE
Django2 compatibility

### ISSUE THREAD

**Issue by elcolie** [justquick/django-activity-stream#396]
I am taking note the issue one by one in here. If any experienced developer can guide me through I would appreciated and submit my `PR`

1. `url.py`
```bash
?: (2_0.W001) Your URL pattern '^activity/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
```

**Comment by auvipy** [comment]
master branch does support django 2.0 and 2.1
