### ISSUE TITLE
Release of 0.6.6 with Django 2.x fixes

### ISSUE THREAD

**Issue by askoretskiy** [justquick/django-activity-stream#401]
Current master branch contains several fixes for newer Django.

Is there any time plan to release 0.6.6 version?

**Comment by jrabbit** [comment]
Any blockers right now?

**Comment by auvipy** [comment]
should be no blocker! master should work well with django 2.1

**Comment by francisbrito** [comment]
@askoretskiy @jrabbit Installing directly from the GitHub repository worked for me: 

`pipenv install git+https://github.com/justquick/django-activity-stream.git#egg=django-activity-stream`

**Comment by sevdog** [comment]
Any news regarding a Django 2.x compliant release?

**Comment by auvipy** [comment]
you can install from github master in the mean time

**Comment by sevdog** [comment]
Our _policy_ does not allow modules to be installed directly from their development branch, so we need a tagged version.

**Comment by meshy** [comment]
I'm unable to install un-versioned requirements, so would also appreciate a release, if possible.

**Comment by pjdelport** [comment]
We're also having to manually pin our releases… can we have a release please? 💜

**Comment by toti1212** [comment]
+1

**Comment by bj00rn** [comment]
@auvipy @justquick can we expect a release 0.6.6 anytime soon?

**Comment by pjdelport** [comment]
Is anything blocking this?

A new release is probably much-needed: it's been almost a year since the last release (0.6.5), and 4 months since this issue was opened. Django 2.0 already ended mainstream support 4 months ago, and ends extended support in 4 months.

If maintainer time is the bottleneck, maybe a move to https://jazzband.co/ could be something to consider? @justquick?

**Comment by auvipy** [comment]
I am actively maintaining this, the problem is Justin didn't have the time to give pypi release access to me. ANd he is busy with personal stuff.

**Comment by auvipy** [comment]
and master is supported with django 2.0 and 2.1 too

**Comment by sevdog** [comment]
> and master is supported with django 2.0 and 2.1 too

At least tag a release, install master branch from GitHub is not considered a best practice for a production environment.

**Comment by pjdelport** [comment]
@auvipy: Understood; I appreciate the work and effort you and @justquick put in. 💜

Do you have any idea when Justin may have time to get you set up with that?

**Comment by auvipy** [comment]
I tried to contact him several ways but seems he might be busy with other stuff.

**Comment by bj00rn** [comment]
@auvipy thanks for your reply. Is the problem that you don't have PyPI credentials? 

If that is the case, could you please create a release tag, so we can use that while we wait for @justquick to publish.

**Comment by auvipy** [comment]
yes. OK sure

**Comment by bj00rn** [comment]
> yes. OK sure

.. did you create the release tag?

(sorry for being a pain in the *ss) 🌹

**Comment by auvipy** [comment]
I got the pypi key. allow me some time to release

**Comment by bj00rn** [comment]
@auvipy sorry for nagging on about this. can you please at least create a pre-release/release git tag that we can use while we wait for a proper release package?

**Comment by justquick** [comment]
0.7.0 is tagged on master and live on pypi

**Comment by pjdelport** [comment]
Thank you! ☕
