### ISSUE TITLE
How to rewrite URL to an object

### ISSUE THREAD

**Issue by gotexis** [justquick/django-activity-stream#403]
By default the stream generated a list and objects with URLs linked to their permanent page. Of course I already made quite a lot of DetailView for these objects. How to modify built-in URL to link to them?

For example, instead of clicking *Client* redirecting to 

`http://site/actstream/32/1/, `

I would like to redirect to 
`http://site/client/1/ `

that I made.

**Comment by gotexis** [comment]
I figured out the best approach will be to supply my own 

`templates/actstream/action.html`
or 
`templates/actstream/verb/action.html`

Actually, I think i18n can be implemented here as well.

If anyone would suggest a better approach I would appreciate it very much.

**Comment by justquick** [comment]
you can setup your own urls module with the views setup however you want. the actstream urls were recently updated
