### ISSUE TITLE
Aggregation timeline

### ISSUE THREAD

**Issue by amitsharma8891** [justquick/django-activity-stream#409]
Hi,

I am creating a system where I need Instagram kind of timeline, where a user can create a post, can follow another user, and can like and share the posts. I wanted to create the aggregated timeline based on users activity on my post

My requirements are:

1. Aggregated timeline (counts of like and share against that user e.g. Bryan and 10 other like this post)
2. If someone does any activity like, share than that post should come at top of my timeline

Please let me know if the above mentioned is possible or not. If yes how can I proceed?

Any help would be highly appreciated.

Thanks

**Comment by zmrenwu** [comment]
Of cause it can, but you have do some tricky database query.

**Comment by slurms** [comment]
This should be possible using `Collections` from: https://www.w3.org/TR/activitystreams-core/#collections.

Hopefully someone can implement something like this, as I'd definitely use it!

**Comment by charlesboutens** [comment]
Hi,
I would really love this feature as well! I tried to aggregate the feed like this:
q = activities.values('verb').annotate(cnt = Count('verb'))

But this doesn't work, as annotations with GFKquerysets don't work properly in Django.

Any solutions for this one? :)
If this need is solved my feed would be finally finished!!

Cheers

**Comment by pfcodes** [comment]
Anybody ever figure this out?
