### ISSUE TITLE
User stream should not display actions prior to the `started` follow date

### ISSUE THREAD

**Issue by raphaelyancey** [justquick/django-activity-stream#411]
I can't see how it is desirable to have an object's notifications that are older than the date the user started following it.

https://github.com/justquick/django-activity-stream/blob/64b23a072fbd297c27a1b28cb0e08dbc4d94fbea/actstream/managers.py#L84

Maybe I'm missing something, but right now, if Alice generates 6 actions and then Bob starts following Alice, Bob will see the 6 actions in his stream.

**Comment by raphaelyancey** [comment]
This code is working but I'm not sure about the performance with large follows/actions list. A review would be nice!

https://github.com/justquick/django-activity-stream/compare/master...Ircam-Web:ftr_recent-user-stream

**Comment by slurms** [comment]
Yup, that'll definitely be slow with lots of objects (one query per object).

It is desirable to have this behaviour though. We should have the default behaviour be the current behaviour and allow passing a keyword argument to enable this.

It should be possible to do in a way that doesn't cripple performance :+1:.
