### ISSUE TITLE
Admin: sort on `actor`

### ISSUE THREAD

**Issue by tobyspark** [justquick/django-activity-stream#413]
Hello,

I've implemented `django-activity-streams` in my project – great stuff, thanks for all the work. I'm now trying to tweak the admin interface. I'd like to be able to sort on the actor column, and my django-fu and google (sort on generic foreign key) have failed me.

Am I missing something obvious? Is there a reason it's not implemented by default? Does anybody have a working implementation (of this or something similar, e.g. search for `action_object`, `target`, other `gfc` fields)?

Toby

**Comment by toti1212** [comment]
Hi @tobyspark, maybe I needed to do something similar. You could resolve this problem? Which approach did you follow?

**Comment by tobyspark** [comment]
For me, this was a "nice to have" not a "have to have"; I moved on to implementing other features.

I'd still like to hear from anybody with any insight to the issue, the technical aspect feels like unfinished business.

**Comment by justquick** [comment]
you can always unregister the current modeladmin and reregister it with one of your own
