### ISSUE TITLE
FETCH_RELATIONS not working

### ISSUE THREAD

**Issue by charlesboutens** [justquick/django-activity-stream#418]
Hi there, 
I am using the latest version 0.7.0 and django 2.1
I have issues prefetching the relations for my feed:

my actstream settings look like:
ACTSTREAM_SETTINGS = {
    'FETCH_RELATIONS': True,
}

and I query my feed via:

activities = user_stream(request.user, with_user_activity=True)

But when I serialize the activities with a genericFieldSerializer for actor / action / action_object etc.. It takes forever because it is making every query individually.

I'm also having the same issues for django-notifications, which is based on this library.

Any ideas? Because otherwise, I love the module 

Kind regards,
Charles

**Comment by pasevin** [comment]
Any updates  on this, I'm having the same issue in the admin.
