### ISSUE TITLE
Customise Action’s content

### ISSUE THREAD

**Issue by saranshbansal** [justquick/django-activity-stream#420]
Hi, I’m using it for the first time and it just took few minutes to set it up and running. However, I have a fixed pattern for the final notification:

[Date/time of comment][User Role][Username] commented on [Target].

I can’t figure out how.

**Comment by cb109** [comment]
The `Action` model has a couple of optional fields (`action_object`, `target`) that you can use to point to things where you can pull back information when displaying the action somewhere. It also has a free-text `description` field that you could e.g. use to some short formatted text. Better suited would be the `data` field (make sure to enable it initially via settings), that stores arbitrary JSON. The datetime is already stored on the `timestamp` field.

To create your notification you would take an `Action` instance, pull information from it and write it to a string or html.
