### ISSUE TITLE
PyPI's django-activity-stream 0.7.0 does not provide the extra 'jsonfield'

### ISSUE THREAD

**Issue by PiDelport** [justquick/django-activity-stream#422]
The version 0.7.0 release of django-activity-stream as tagged on GitHub includes PR #392 with the `extras_require` definition for `jsonfield`, but actual 0.7.0 package that's on PyPI does not include this, and may have been built from a different revision as the one actually tagged on GitHub?

This means that trying to install `django-activity-stream[jsonfield]` fails:

```
$ pip install django-activity-stream[jsonfield]
Collecting django-activity-stream[jsonfield]
  Downloading https://files.pythonhosted.org/packages/2c/0c/a6cce7dc4f26e3615ae684a419cf6e02434e1e4dbaaf50d9bd5b1340a840/django-activity-stream-0.7.0.tar.gz
  django-activity-stream 0.7.0 does not provide the extra 'jsonfield'
…
```

**Comment by morenoh149** [comment]
the 0.8.0 version of the project is on pypi https://pypi.org/project/django-activity-stream/#history does that fix your issue?

**Comment by benspaulding** [comment]
Unfortunately the 0.8.0 release on PyPI doesn’t fix it either — it is also missing the `extras_require`. There must be some issue when creating the distribution. 🤷🏻‍♂️

**Comment by justquick** [comment]
fixed in recetn releases
