### ISSUE TITLE
Docs clarification about how to use custom data in actions

### ISSUE THREAD

**Issue by timur-orudzhov** [justquick/django-activity-stream#431]
I suppose, docs needs clarification about how to use custom data in actions:

First of all, for json field support django-actstream uses two third party libraries: django-jsonfield, django-jsonfield-compat.

Second, i think would be useful, to point out how to disable jsonfield-compat, cause django > 1.9 already has json field implementation, if postgresql is used as db, because these fields implementation behaves differently: jsonfield-compat renders itself as string, while django's json field renders itself as json object. In order to disable jsonfield-compat, we should set this in settings and rerun migrations:

```python
# settings for disable jsonfield-compat and use django's built-in json field
USE_NATIVE_JSONFIELD = True
```

Thanks!

**Comment by cb109** [comment]
I agree that the docs about enabling the `data` `JSONField` can be improved :+1: 

One thing ahead: `django-jsonfield` is a pseudo-jsonfield (actually a `TextField`) from a time before Django offered native jsonfield options. `django-jsonfield-compat` is a compatibility layer on top of that that decides whether to use the former or rely on a native option, based on the database and django version used. So they belong together.

Digging into it, I don't even know why `USE_NATIVE_JSONFIELD` exists. When `USE_JSONFIELD` is set and the libraries installed, `django-jsonfield-compat` will prefer the native field anyway. Maybe it can go away to simplify the whole process. I don't see a reason to get rid of `django-jsonfield-compat`, as it offers flexibility and backwards compatibility for those stuck on older Django versions.
