### ISSUE TITLE
Can you post a new version on pypi?

### ISSUE THREAD

**Issue by missuor** [justquick/django-activity-stream#433]
Tags
0.7.0  …
 on 14 Dec 2018   b2f651d   zip   tar.gz
0.6.5  …
 on 21 Jan 2018   f8f71d2   zip   tar.gz

**Comment by missuor** [comment]
I have to do something like this
```
sed -e "s/print('JSONField implementation is/#print('JSONField implementation is/g" $(python -c "import actstream;print actstream.__file__.replace('__init__','jsonfield').replace('.pyc','.py')")
```

**Comment by auvipy** [comment]
I am going to push one today

**Comment by auvipy** [comment]
https://pypi.org/project/django-activity-stream/0.8.0/

**Comment by cb109** [comment]
Hey @auvipy thank you for pushing to pypi, I can finally remove the github URL from my requirements.txt ;) Could you please take a moment and add actual Releases on Github with a small changelog stating what kind of features/fixes 0.7.0 and 0.8.0 include? I would really appreciate that, thanks!

**Comment by auvipy** [comment]
definitely I can, plz ping me if i forget

**Comment by cb109** [comment]
@auvipy ping :)

**Comment by GertBurger** [comment]
@auvipy ping :)
