### ISSUE TITLE
Using CharField on GFK object id hinders GenericRelation lookups

### ISSUE THREAD

**Issue by pandabearcoder** [justquick/django-activity-stream#434]
Why is the target_object_id and actor_object_id have the field set to CharField. This creates problem when trying to create a GenericRelation back to this model. This results to `You might need to add explicit type casts` when trying to do a related object lookup

**Comment by edison7500** [comment]
https://stackoverflow.com/questions/3625641/django-queryset-custom-ordering-by-id
