### ISSUE TITLE
[Feature request] Setting to disable admin?

### ISSUE THREAD

**Issue by David-Guillot** [justquick/django-activity-stream#436]
Hi there,

I'd like to know if you would agree to add some setting to avoid registering admins in the main admin site. I know i can override the default admin site and unregister some stuff, but if apps expose such settings, life would be easier, no?

If you agree, i can open a PR in the next few days ; the code change would basically be:

* Remove [these 2 lines](https://github.com/justquick/django-activity-stream/blob/master/actstream/admin.py#L28-L29)
* Move them [here](https://github.com/justquick/django-activity-stream/blob/master/actstream/apps.py#L14), conditioned to a setting named `REGISTER_ADMINS`

What do you think?

**Comment by justquick** [comment]
you can import teh admin registry and unregister the fields
