### ISSUE TITLE
Create stream for team/organization

### ISSUE THREAD

**Issue by cobyrne09** [justquick/django-activity-stream#445]
I would like to create a stream for a team/organization of users, apart from the follow/unfollow functionality. Each member of the team would be able to see the activity of their respective team. My team/organization model is not involved in any actions, it is simply an abstraction layer of my user model. My 'actors' are always users, and never teams as a whole. Can this be achieved through 'Actor Streams' or another existing method? Or will I need to create a custom stream? Looking through the code base, I can't figure out how to achieve this, and there don't seem to be others interested in this based on the github issues. I would have thought it was a moderately common use case 🤷‍♂️.

I recognize I could 'hack' this by forcing every user to follow every other user on the team, and then using a 'User stream', but I would prefer not to do this, for reasons that are not relevant to the question. 

Thanks for any guidance and for a great package.

**Comment by auvipy** [comment]
it is your project-specific need I think.

**Comment by cobyrne09** [comment]
@auvipy meaning you don't think it's possible? How would you recommend going about it? Even if it seems project specific, I could see it being beneficial to others, who may be trying something similar, although different.

**Comment by cobyrne09** [comment]
if anyone else comes across this scenario and would like a starting point, here is my code: `from actstream.managers import ActionManager, stream
from actstream.registry import check
from pprint import pprint

from accounts.models import User


class MyActionManager(ActionManager):

    @stream
    def organization_stream(self, obj, **kwargs):
        """Create a stream of the most recent actions by objects that the user is following."""
        q = Q()
        qs = self.public()

        if not obj:
            return qs.none()

        content_type = ContentType.objects.get_for_model(User)
        # get team members for organization object
        organization_members = obj.user_set.values_list('id').all()
        # convert UUID's to string for query
        organization_members = [str(o) for o in organization_members[0]]

        # query for where content type is the user model and the actor is an organization member
        q = q | Q(
            actor_content_type=content_type.pk,
            actor_object_id__in=organization_members
        ) 

        return qs.filter(q, **kwargs)`
