### ISSUE TITLE
Pagination and django-activity-stream

### ISSUE THREAD

**Issue by cobyrne09** [justquick/django-activity-stream#448]
Is there any guidance on how to use django-activity stream with pagination? Or at least limit the results returned to the last N results?

**Comment by cb109** [comment]
@cobyrne09 Both querying `Action` objects directly or through one of the stream helpers (e.g. `any_stream(my_user)` will give you a `actstream.gfk.GFKQuerySet`, and QuerySets support slicing. So to limit to the last 10 results you can do:

```py
any_stream(my_user)[:10]
```

You can `.order_by("timestamp")` to reverse the order.
