### ISSUE TITLE
A new release with django 3 compatibility

### ISSUE THREAD

**Issue by tasn** [justquick/django-activity-stream#453]
master already supports django3 thanks to #438.
Please make a release (0.8.1 or 0.9.0) that includes these fixes so we can update to django3.

Thanks.

**Comment by breslavsky** [comment]
It is really required for our team too.

**Comment by auvipy** [comment]
please conider some donation for my time on this.

**Comment by mattonit** [comment]
@justquick could you please do that?

**Comment by xgenvn** [comment]
Longing to the new release as well, my team can resist upgrading to Django 3

**Comment by thibaut-singlefile** [comment]
In the meantime, you can create a dependency on the specific commit in your Pipfile:
`django-activity-stream = {git = "git://github.com/justquick/django-activity-stream.git",ref = "8d38fd45b4bef1f7137fb8185b04ee0d8cdb5e3b"}`
This worked for me with Django 3.

**Comment by awbacker** [comment]
@auvipy You could nominate someone to help manage the project, or handover, if the financial or time burden is too high.  Running a project like this is challenging, and I thank @justquick for putting this up for us and saving me a lot of trouble and work.  Much appreciated, and I'll use it as an inspiration for something that fits my requirements better.

@auvipy IMO its abandoned after reading your comment (not a bad thing, it happens frequently).  Thanks for the heads up.

In the meantime, if you have a private pypi you can fork it and publish privately (what I'll do) or pin as mentioned by @thibaut-singlefile (thanks for the snippet!)

**Comment by jadhavmanoj** [comment]
does this support python3.7 version as well? I dont see in the document but is there a way we can use with python3.7

**Comment by mattonit** [comment]
@jadhavmanoj I had some issues with Python 3.7 and Django 3, but I managed to use it with this setup

**Comment by GitRon** [comment]
Also looking forward to the new release! Any news about it so far?

**Comment by RailRunner166** [comment]
this module is just the right solution for what i'd like to do in my application, would be nice to see it updated to work with django 3 so i can actually use it ❤️

**Comment by auvipy** [comment]
done! feel free to contribute some donation for this project!
