### ISSUE TITLE
Action.data not deserialized with django-jsonfield >= 1.3.0

### ISSUE THREAD

**Issue by Mapiarz** [justquick/django-activity-stream#457]
Hi

I've been using django-activity-stream for quite some time and it works as intended with psql and django-jsonfield <= 1.2.0. If I update jsonfield to 1.3.0 or more recent, the `data` field is no longer deserialized and instead a string is returned. This is happening due to this change in jsonfield: https://github.com/adamchainz/django-jsonfield/pull/14.

**Comment by lociii** [comment]
This has been resolved in the now merged #474 by switching from django-jsonfield to the built-in or backported json field implementation
