### ISSUE TITLE
AnonymousUser problem get request with postman

### ISSUE THREAD

**Issue by burakkilicaslan** [justquick/django-activity-stream#459]
Hello everyone, 

I got a problem, I hope you can help me. 
I create a web application with django rest and use vue.js for frontend. So I test my endpoints with postman. 
I override feeds.py due to my project issues, and I want to take feeds activities for following users. 
Everything went perfect, I can take user actions that logged in user follows. 

However, when I try this endpoint with postman, request.user comes as anonymous user. So I can't take actions. But I try it with Django rest on my browser, request user comes as logged in user. 
I put my feeds.py jsonactivityfeed class which is overrided from act stream/feeds.py and I try to show where it is. 

```
class JSONActivityFeed_Activity_2(Abstract_Activity_Stream_2, View):

    def dispatch(self, request, *args, **kwargs):
        data = self.serialize(request, *args, **kwargs)
        print(request.user) # this comes as anonymous user from postman 
        return JsonResponse(data, safe=False)
```
I couldn't understand why it is that, I use in my project simple jwt and give bearer token when I test with postman. 

If anybody can help me, I appreciate that.

**Comment by mhoonjeon** [comment]
I'm having similar problems here. I think this library does not obey the DRF's authentication classes settings. Did you find a workaround?

**Comment by justquick** [comment]
drf is outside the scope of this project. that being said there are a lot off requests coming from people who are using it. will look ingo changes
