### ISSUE TITLE
implementing Federation

### ISSUE THREAD

**Issue by barslmn** [justquick/django-activity-stream#464]
Greetings,

How do you go about implementing federation on top of django-activity-streams? Would I be rewriting unnecessary stuff if I follow [this example](https://github.com/tOkeshu/activitypub-example).

Thanks,
B

**Comment by justquick** [comment]
This sounds like a good idea but the django activitypub example you gave is a django site not a reusable app. Is there a django reusable app for the activitypub federation implementation or will I have to create one?

**Comment by barslmn** [comment]
I think I come across few as apps. This might be the best example : https://dev.funkwhale.audio/funkwhale/funkwhale/-/tree/develop/api/funkwhale_api/federation

**Comment by justquick** [comment]
that app uses drf which this isnt really setup to use. you would simply need to make a client on either end to consume the feeds the app creates
