### ISSUE TITLE
Django 2.2 support?

### ISSUE THREAD

**Issue by zehawki** [justquick/django-activity-stream#469]
https://django-activity-stream.readthedocs.io/en/latest/installation.html says these are the following versions supported: Django: 1.3, 1.4, 1.5, 1.6, 1.7, 1.8 and 1.9

Is this right, or are the docs simply outdated, and things work just fine for Django 2.2?

**Comment by MrCordeiro** [comment]
I was also confused by this.

**Comment by Uninen** [comment]
According to the changelog, Django 2.2 and 3.0 are supported: https://github.com/justquick/django-activity-stream/blob/master/docs/source/changelog.rst

**Comment by lociii** [comment]
Docs have already been fixed, see https://github.com/justquick/django-activity-stream/blob/master/docs/source/installation.rst they just haven't been regenerated and deployed since 1dbc0f0693052bc1f54870732dc717d3a622c39f

**Comment by auvipy** [comment]
https://pypi.org/project/django-activity-stream/0.10.0/

**Comment by lociii** [comment]
0.10.0 release did not update readthedocs.
Will try to find the time for a pull request to add readthedocs publication to the build.
