### ISSUE TITLE
Filtering out actions

### ISSUE THREAD

**Issue by jcampbell05** [justquick/django-activity-stream#470]
I'm using this to power a marketplace feed.

I want the ability to be able to fetch the current state of an object to show to the user its sold or be able to filter stout all together.

Is this possible ?

**Comment by auvipy** [comment]
you need to dig the codes to figure out

**Comment by justquick** [comment]
i would send the action signal when an item is sold or sold out. that would show up in their stream
https://django-activity-stream.readthedocs.io/en/latest/actions.html
