### ISSUE TITLE
Next Release / 3.1 Support

### ISSUE THREAD

**Issue by dstarner** [justquick/django-activity-stream#476]
I was looking forward to a new release since [the 3.1 support for `JSONField` was added in](https://github.com/justquick/django-activity-stream/pull/474).

When can we expect a new version to be cut? Does anything else need to be done before that can happen?

**Comment by auvipy** [comment]
just changelog and release. allow me till tomorrow or ping me if I forget

**Comment by dstarner** [comment]
Awesome, thank you!

**Comment by dstarner** [comment]
@auvipy ping 😄

**Comment by auvipy** [comment]
releaseing in an hour :D

**Comment by auvipy** [comment]
https://pypi.org/project/django-activity-stream/0.10.0/
