### ISSUE TITLE
Sending to only one user?

### ISSUE THREAD

**Issue by karx1** [justquick/django-activity-stream#478]
Hey guys, I'm building a chat application and I want to send notifications to users when a message is sent to them. However, `action.send` seems to be sending the notification to every user following the sender. Obviously, this is not good for privacy.

How do I make the `action.send` function send the action to only one user's stream?
Thanks in advance.

**Comment by justquick** [comment]
the signal simply creates the models. how you want to send the user notifications is up to you. you can filter out the notifications for whatever way you are sending them to the end user. but that's part of your project and not this app
