### ISSUE TITLE
Reloading django apps is problematic

### ISSUE THREAD

**Issue by v1kku** [justquick/django-activity-stream#480]
In [apps.py](https://github.com/justquick/django-activity-stream/blob/master/actstream/apps.py#L28-L36) `django_jsonfield_backport` is added to `INSTALLED_APPS` and django is forced to reload the apps. This is problematic for projects that perform non-idempotent operations in their apps' `ready` method. 3rd party packages should not be doing this. Can't that check just report an error asking the user to add `django_jsonfield_backport` to `INSTALLED_APPS` (and a warning that reminds them to remove it if django>=3.1)? I'm happy to make a PR for that

**Comment by auvipy** [comment]
@lociii what do you suggest?

**Comment by lociii** [comment]
Sounds good to me.
However this will be a breaking change as activity stream will stop working with JSON data field when the update is installed and `django_jsonfield_backport ` is not added to the `INSTALLED_APPS `.

**Comment by justquick** [comment]
go ahead and make a PR so we can see the solution
