### ISSUE TITLE
with_user_activity not filtering out actions by request.user

### ISSUE THREAD

**Issue by rollue** [justquick/django-activity-stream#482]
```python
from actstream.models import user_stream

qs = user_stream(user, with_user_activity=False)  # or user_stream(user)
```
qs should exclude actions which the user is the actor, but it is not.

Am I misunderstanding the purpose of the with_user_activity flag?

**Comment by justquick** [comment]
user_stream: `Create a stream of the most recent actions by objects that the user is following.`
doesnt exclude actions where the user is actor
try adding your own https://django-activity-stream.readthedocs.io/en/latest/streams.html#writing-custom-streams
