### ISSUE TITLE
How to set a custom JSONField.encoder

### ISSUE THREAD

**Issue by todorvelichkov** [justquick/django-activity-stream#489]
We are updating out app from `Django 2.2 + django-activity-stream==0.8.0` to `Django 3.2 + django-activity-stream==0.10.0`

In version `0.8.0` django-activity-stream used to work with `jsonfield_compat` where [JSONFIELD_ENCODER_CLASS](https://github.com/kbussell/django-jsonfield-compat/blob/master/jsonfield_compat/compat.py#L17) can be used as a setting in order to set a custom `JSONField.encoder`. No such options exists anymore for Django's `JSONField`.

**Comment by auvipy** [comment]
that was used for compatibility reason which is not needed in newer versions

**Comment by todorvelichkov** [comment]
I'm sorry @auvipy  but I cannot understand you, what do you mean by "not needed"? Is there a way to provide an "encoder" kwarg to  [JSONField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#jsonfield)? Our app is storing data in `Action.data` which cannot be encoded with the default `json.JSONEncoder` so we definitely need this.

**Comment by auvipy** [comment]
you can dig codes and find a solution, if that change is needed upstream, contributions are welcome.
