### ISSUE TITLE
The model User is not registered. Please use actstream.registry to register it.

### ISSUE THREAD

**Issue by zyjswiadomielife** [justquick/django-activity-stream#490]
Hi, I try to register user. I find other posts with this (eg. https://github.com/justquick/django-activity-stream/issues/216)

But not work for me. I have Django 3.1.7 version.

I create new app for this: regstreams, and then add this code to apps.py:

```
from django.apps import AppConfig, apps
from actstream import registry

class ActivityConfig(AppConfig):
    name = 'regstreams'

    def ready(self):
        registry.register(apps.get_model('auth.User')) 
```
And in __init__.py

`default_app_config = 'regstreams.apps.ActivityConfig'`

But still I have error: 
```
raise AppRegistryNotReady("Apps aren't loaded yet.")
| django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Please help. 

Ok I get solution. Just move from actstream import registry to def ready(self) like this:
```

    def ready(self):
        from actstream import registry
        registry.register(apps.get_model('auth.User')) 
```

**Comment by sklaghari** [comment]
def ready(self):
        from actstream import registry
        from django.contrib.auth.models import User
        registry.register(User)
register inside ready function instead of outside
