### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by suprmat95** [justquick/django-activity-stream#491]
I am developing a web and mobile application in which I use session authentication.

I would like to test all endpoints but some of them are protected by the @login_required and @csrf_exempt decorators.

For example when I try to do  GET http://localhost:8000/activity/follow/<content_type_id>/<object_id> the login form appears and after login an error appears about the csrf. Do you how I can solve this issue?

![image](https://user-images.githubusercontent.com/11753185/123944784-beda4300-d99d-11eb-84f2-61490b548d38.png)

![image](https://user-images.githubusercontent.com/11753185/123944984-f77a1c80-d99d-11eb-844c-0679c74e891d.png)

**Comment by justquick** [comment]
looks like you are using token auth with drf. token auth doesnt work well w/ csrf. you can subclass the view and use the @csrf_excempt decorator (with caution) or find another way around it 

https://stackoverflow.com/questions/30871033/django-rest-framework-remove-csrf
