### ISSUE TITLE
django 4.0 support

### ISSUE THREAD

**Issue by auvipy** [justquick/django-activity-stream#495]

**Comment by justquick** [comment]
Have a solution in the django4 branch. give it a try and see if it's working

**Comment by j-gooding** [comment]
Is there an ETA when this might be released?

**Comment by auvipy** [comment]
may be in 2 weeks

**Comment by justquick** [comment]
Yea as long as this is reviewed ok I can release it

**Comment by auvipy** [comment]
ok
