### ISSUE TITLE
django-activity-stream and django-comments-xtd

### ISSUE THREAD

**Issue by pnizet** [justquick/django-activity-stream#499]
Hello,
[disclaimer : noob question]
On a django project i'm using both [django-activity-stream](https://github.com/justquick/django-activity-stream) and [django-comments-xtd](https://github.com/danirus/django-comments-xtd), Is there a way to build a stream of the comments posted via the django-comments-xtd package ??
because obviously I will not modifiy the code of the package... to add action in it
How am I supposed to do so ??
Thanks for your help

**Comment by auvipy** [comment]
ask on StackOverflow

**Comment by justquick** [comment]
you can always use the actstream signals to send/recieve info. eg django's post_save can detect comment model changes and then you can use the actions signals to configure your project as you want

https://django-activity-stream.readthedocs.io/en/latest/actions.html
https://docs.djangoproject.com/en/4.0/topics/signals/
