### ISSUE TITLE
Make a 2.0 release and publish to PyPI

### ISSUE THREAD

**Issue by mattrei** [justquick/django-activity-stream#531]
Hi,

according to your [comment](https://github.com/justquick/django-activity-stream/pull/503#issuecomment-1426573103)  you have merged the branch to use this lib with DRF.

However its not published yet on PyPI and no new release has been made.

Thanks for making a new release to enjoy the new features!

**Comment by auvipy** [comment]
OK I will release a new version. can you try the main branch and verify that codes are working as normal

**Comment by mattrei** [comment]
hi. thanks.
yes the code seems to be working. Just using the DRF modules though. Did not run over any issues so far.

However we I do not get is how can i also retrieve/save the type of object or type of actor when creating an action event.

For instance looking at the example: 
`[justquick](https://github.com/justquick/) (actor) closed (verb) [issue 2](https://github.com/justquick/django-activity-stream/issues/2) (object) on [django-activity-stream](https://github.com/justquick/django-activity-stream/) (target) 12 hours ago`

I also want to save what kind of target or what kind of object it is (= the Model class of the target and object). 
Can this be achieved somehow?

Thankxs for making a new release!

**Comment by iamMHZ** [comment]
@auvipy 
Any progress on this ?

**Comment by auvipy** [comment]
hopefully this week
