### ISSUE TITLE
Update docs to display support up to Python 3.12 and Django 5.0?

### ISSUE THREAD

**Issue by wgordon17** [justquick/django-activity-stream#539]
Hey all (and @justquick), I've been doing some local work on `django-activity-stream` because I honestly didn't trust the doc's assertion that this is only supported up to Python 3.9 and Django 4.1 😅

I've managed to get `tox` and `pytest` passing for _all_ environments now (a few _minor_ tweaks to the `tox.ini`) with the exception of [this specific text](https://github.com/justquick/django-activity-stream/blob/main/actstream/tests/test_activity.py#L279) for Django 5.0. Commenting out that line allows for the rest of the tests to succeed with Django 5.0, and I've opened a thread in the Django Discord to see if there was an undocumented breaking change here that causes the translated text to no longer be stored in the database as `LANGUAGE_CODE`.

Once I get that sorted, do you have any concerns with me submitted a PR with the updated `tox.ini` changes, any changes I might need to do to resolve that specific test, and a docs update to reflect the changed support?

**Comment by wgordon17** [comment]
Alrighty, problem identified, https://forum.djangoproject.com/t/new-5-0-behavior-storing-translated-string-in-database-solved/29483/5, and a PR is on it's way. Thankfully, this repo supports all the way up to 3.12 without any changes, but just needs a minor change to account for changes in Django 5.0 🎉

**Comment by simkimsia** [comment]
Just wanted to add that the docs don't seem to be updated as well. https://django-activity-stream.readthedocs.io/en/latest/changelog.html

Is this supporting Django 4.2?
